## 分车型预测

In [1]:
import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.layers import *
from keras.models import *
from keras.callbacks import *
from keras.optimizers import *
import matplotlib.pyplot as plt
from keras import backend as K
from keras.utils import plot_model
from keras.models import Sequential
from keras.engine.topology import Layer
from keras.layers import Dense, Dropout
from keras.initializers import glorot_uniform
from keras.layers import LSTM, RNN, GRU, SimpleRNN, Bidirectional, BatchNormalization
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import initializers, regularizers, constraints, optimizers, layers
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.initializers import glorot_uniform

# from IPython.core.interactiveshell import InteractiveShell 
# InteractiveShell.ast_node_interactivity = 'all'    # 默认为'last'

seed = 2019
random.seed(seed)
tf.set_random_seed(seed)
np.random.seed(seed)
warnings.filterwarnings('ignore')

C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: P

In [2]:
data_path = './data/'
train_user_reply_data = pd.read_csv(data_path + 'train_user_reply_data.csv', encoding='utf-8')
train_search_data = pd.read_csv(data_path + 'train_search_data.csv', encoding='utf-8')
train_sales_data = pd.read_csv(data_path + 'train_sales_data.csv', encoding='utf-8')
evaluation_public = pd.read_csv(data_path + 'evaluation_public.csv', encoding='utf-8')

train_sales_data = train_sales_data.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True)
evaluation_public = evaluation_public.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True)

In [3]:
cars = ['a50a6db3d691e9ce', 'b135f55ced5c4c67', '9011c3cf495e3c7b', '28e29f2c03dcd84c', '54fc07138d70374c', 'd0f245b8781e3631', 'ffeb3a4cec627e8c', 'a7128d308ae14d73', '7aab7fca2470987e', '42d4439853da7221', '2509a94e62fd3e4b', '9e967965ad4a6c07', '346393c2c6305fb1', '7a7885e2d7c00bcf', '17bc272c93f19d56', 'f8a6975573af1b33', 'feabbf46658382b9', 'fde95ea242abd896', 'd4efbebb087fd03f', '04e66e578f653ab9', '7245e0ee27b195cd', 'f270f6a489c6a9d7', '02aab221aabc03b9', 'b4be3a4917289c82', 'f5d69960089c3614', 'c06a2a387c0ee510', '6858d6dfe680bdf7', '12f8b7e14947c34d', '07a30393ec51530e', 'cc21c7e91a3b5a0c', '3c974920a76ac9c1', '37aa9169b575ef79', 'ea489c253676aafc', '97f15de12cfabbd5', 'fc32b1a017b34efe', 'b25c4e2e3856af22', '854982e5264fb53e', '8527c11fccaa94e2', '283d331fdf05a655', '9a390098bf87b814', 'a28bb927b6fcb33c', 'a9a43d1a7ecbe75d', 'ef76a85c4b39f693', '4a103c30d593fbbe', '0797526c057dcf5b', 'c6cd4e0e073f5ac2', '1181894ae2811540', 'af6f4f548684e14d', '6155b214590c66e6', '5b1c11c3efed5312', '936168bd4850913d', 'c6833cb891626c17', '8cbac8dd8f0e89e2', 'a432c483b5beb856', 'cd5841d44fd7625e', '2a2ab41f8f6ff1cb', '7023efdab9cedc03', 'bb9fbec9a2833839', '79de4e4b24c35b04', '4f79773e600518a6', '28956642949e0e57', '3d7554f1f56dd664', 'b9aa8592ab2492da', '17363f08d683d52b', 'bc5bbd459c18fefd', '0aa15031db420212', '3e21824be728cbec', '7cf283430b3b5e38', '212083a9246d2fd3', 'da457d15788fe8ee', 'a207df29ec9583f0', '2d0d2c3403909fdb', '8c915fe4632fb9fa', '06880909932890ca', 'dff803b4024d261d', '63065128401bb3ff', '9c1c7ee8ebdda299', 'e8a33f68c15dcf7c', '32d3069d17aa47c2', '5f727f32393ade77', '5d7fb682edd0f937', '61e73e32ad101892']
provinces = ['浙江', '福建', '四川', '陕西', '安徽', '湖南', '广东', '云南', '上海', '山东', '湖北', '黑龙江', '江苏', '广西', '内蒙古', '辽宁', '北京', '重庆', '河北', '山西', '江西', '河南']

print(len(cars))
print(len(provinces))

# Normalization
train_sales_data['salesVolume'] = train_sales_data['salesVolume'].map(lambda index: np.log2(index) + 1)
scaler = MinMaxScaler(feature_range=(0, 1))
train_sales_data[['salesVolume']] = scaler.fit_transform(train_sales_data[['salesVolume']])
train_sales_data.head(3)

82
22


province  adcode             model bodyType  regYear  regMonth  \
506       上海  310000  02aab221aabc03b9    Sedan     2016         1   
507       云南  530000  02aab221aabc03b9    Sedan     2016         1   
508      内蒙古  150000  02aab221aabc03b9    Sedan     2016         1   

     salesVolume  
506     0.666707  
507     0.567856  
508     0.469225

In [4]:
def generate_batch(data_set, look_back, gap_days):
    data_x, data_y = [], []
    for i in range(len(data_set) - look_back - gap_days + 1):
        a = data_set[i:(i + look_back), 0]
        data_x.append(a)
        data_y.append([data_set[i + look_back + gap_days - 1, 0]])
    return np.array(data_x), np.array(data_y), data_set[-look_back:, 0].reshape(1, look_back)

def generate_first_order_batch(data_set, look_back, gap_days):
    data_x = []
    for i in range(len(data_set) - look_back - gap_days + 1):
        a = data_set[i:(i + look_back), 0]
        data_x.append(a)
    return np.array(data_x), data_set[-look_back:, 0].reshape(1, look_back)

In [5]:
def metrics(data):
    data = scaler.inverse_transform(data)
    data = 2 ** (data - 1)
    print(data)
    
    a = data[:, 0]
    b = data[:, 1]
    res = np.sqrt(np.sum((a - b) ** 2) / len(a)) / np.mean(a)
    print('validate rmse:', 1 - res)
    return (1 - res)

In [6]:
from keras.layers.advanced_activations import PReLU

def construct_lstm_model(x_train, x_test, y_train, y_test, test, car_name, batch_size):
    print('batch_size:', batch_size)
    input1_ = Input(shape=(1, look_back), name='input1', dtype='float32')
    input2_ = Input(shape=(1, look_back), name='input2', dtype='float32')

    seq1 = LSTM(32, return_sequences=True, kernel_initializer=glorot_uniform(seed=seed))(input1_)    # , input_shape=(1, look_back)   GRU   LSTM
    seq1 = LSTM(32, return_sequences=False, kernel_initializer=glorot_uniform(seed=seed))(seq1)

    seq2 = LSTM(32, return_sequences=True, kernel_initializer=glorot_uniform(seed=seed))(input2_)
    seq2 = LSTM(32, return_sequences=False, kernel_initializer=glorot_uniform(seed=seed))(seq2)

    merged = concatenate([seq1, seq2])
    merged = BatchNormalization()(merged)
    merged = Dropout(0.5)(merged)
    output_ = Dense(units=1, kernel_initializer=glorot_uniform(seed=seed))(merged)
    output_ = PReLU()(output_)
    model = Model(inputs=[input1_, input2_], outputs=[output_])
    model.compile(loss='mean_squared_error', optimizer='adam')              # AdamW(weight_decay=0.08)   'adam'
#     model.summary()
    early_stopping = EarlyStopping('val_loss', patience=20, verbose=1)
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=0.00001, verbose=0)
    best_model_path = './model/' + car_name + '.h5'
    checkpoint = ModelCheckpoint(best_model_path, monitor='val_loss', mode='min', save_best_only=True, verbose=0, save_weights_only=False)
    
    callbacks = [early_stopping, reduce_lr]         # checkpoint   # reduce_lr
    model.fit([x_train[:, :, :look_back], x_train[:, :, look_back:]], y_train, epochs=500, batch_size=batch_size, verbose=0, shuffle=False, callbacks=callbacks, validation_data=([x_test[:, :, :look_back], x_test[:, :, look_back:]], y_test))
#     model.load_weights(best_model_path)     # load best model parameters   shuffle=False
    predict = model.predict([test[:, :, :look_back], test[:, :, look_back:]])
    predict = scaler.inverse_transform(predict)
    predict = 2 ** (predict - 1)
#     print(np.hstack((y_test, model.predict(x_test))))
    rmse = metrics(np.hstack((y_test, model.predict([x_test[:, :, :look_back], x_test[:, :, look_back:]]))))
    return predict, rmse

In [7]:
file_name = os.listdir('./model/')

look_back = 9     # 10  9
label_length = 4
batch_size = 16
submit = pd.DataFrame()
flag = 0
total = []
thresh = 1.2368

for car in cars:
    labels = np.zeros([len(provinces), label_length])
    rmse_total = 0
    for k in range(1, 5, 1):
        print('{} car:{}'.format(flag+1, car))
        train = np.array([[0 for _ in range(look_back)]])
        train_feature = np.array([[0 for _ in range(look_back)]])
        label = np.array([[0]])
        test = np.array([[0 for _ in range(look_back)]])
        test_feature = np.array([[0 for _ in range(look_back)]])

        for province in provinces: 
            temp = train_sales_data[(train_sales_data['model'] == car) & (train_sales_data['province'] == province)]
    #         print(temp[['province', 'model', 'regYear', 'regMonth', 'salesVolume']])
            temp['first_order'] = temp['salesVolume'].diff(1)

            data = temp['salesVolume'].values.reshape(-1, 1).astype('float32')[1:]
            data_b = temp['first_order'].values.reshape(-1, 1).astype('float32')[1:]

            train_data, train_label, test_data = generate_batch(data, look_back, k)
            train_data_b, test_data_b = generate_first_order_batch(data_b, look_back, k)

            train = np.vstack((train, train_data))
            label = np.vstack((label, train_label))
            test = np.vstack((test, test_data))
            train_feature = np.vstack((train_feature, train_data_b))
            test_feature = np.vstack((test_feature, test_data_b))

        train = np.hstack((train, train_feature))
        test = np.hstack((test, test_feature))
        train = train[1:]
        label = label[1:]
        test = test[1:]
        train = np.reshape(train, (-1, 1, look_back * 2))
        test = np.reshape(test, (-1, 1, look_back * 2))
        x_train,x_test,y_train,y_test = train_test_split(train, label, test_size=0.1, random_state=seed)

        print('train shape:', train.shape)
        print('label shape:', label.shape)
        print('test shape:', test.shape)
        res, rmse = construct_lstm_model(x_train, x_test, y_train, y_test, test, car, int((train.shape[0] * 0.9) / 22))

        K.clear_session()    #  清除tf session

        labels[:, k-1] = res.reshape(1, -1)
        rmse_total += rmse
    print(labels)
    print('average rmse:', rmse_total / 4)
    flag += 1
    total.append(rmse_total / 4)

    index = 0
    submit_partial = pd.DataFrame()
    for province_2 in provinces: 
        temp = evaluation_public[(evaluation_public['model'] == car) & (evaluation_public['province'] == province_2)]
        temp['forecastVolum'] = labels[index]
        submit_partial = pd.concat([submit_partial, temp], axis=0)
        index += 1
    submit = pd.concat([submit, submit_partial], axis=0)

print('all validation rmse:', np.mean(total))  # 0.6555167883490066
car_rmse = pd.DataFrame({'cars': cars, 'rmse': total})
print(car_rmse)
# car_rmse.to_csv('car_rmse.csv', encoding='utf-8', index=None)

[]
1 car:a50a6db3d691e9ce
train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00050: early stopping
[[505.99990097 409.2824898 ]
 [205.00005415 201.67704044]
 [277.00001148 240.36235554]
 [186.99997475 219.29153903]
 [ 69.9999972   59.92313646]
 [108.00001109  86.58537882]
 [438.99998416 409.88593771]
 [456.99998136 349.27470109]
 [129.00003593 116.08624604]
 [215.9999768  150.45722625]
 [291.00005581 226.7024095 ]
 [146.99999695 121.21439178]
 [155.99997376 188.55668893]
 [326.00008753 282.558394  ]
 [469.00003486 451.90698109]
 [279.0000113  295.28760309]
 [250.9999714  199.67085678]
 [179.99997496 153.68630964]
 [174.00002648 103.26565305]
 [245.00000606 331.12364337]
 [208.99994294 145.75790427]
 [ 76.00000245  63.13906294]
 [ 45.99999794  48.67378922]
 [145.99997893 160.83667871]
 [146.99999695 258.20823935]
 [285.99997371 301.84841122]
 [551.00014181 421.08858791]
 [246.99996538 179.70637813]
 [ 96.00000781  87.54404892]
 [263.99994088 237

Epoch 00057: early stopping
[[ 146.99999695  173.02471397]
 [ 233.00000251  169.00863355]
 [1020.00018486  686.49030389]
 [ 371.00004081  262.91748685]
 [  76.00000245  109.83341225]
 [ 179.99997496   93.65728221]
 [ 384.00009048  297.84498664]
 [ 407.99997673  374.62757278]
 [ 233.00000251  180.55967038]
 [ 308.00004471  251.06976067]
 [ 121.99999587  114.91553564]
 [  93.00000537   75.64112263]
 [ 464.00005273  245.96644549]
 [ 145.00001747  140.03877062]
 [1803.00025245  678.04050985]
 [ 182.99997653  185.63430761]
 [ 120.99999821  127.28442535]
 [  69.9999972    82.66484159]
 [ 336.00004907  180.49558759]
 [  67.99999205  141.37797993]
 [ 479.00013488  387.31087643]
 [  73.0000048   118.20674048]
 [ 195.99997326  244.23102017]
 [  92.00000298  110.89634338]
 [  78.00000326   79.18109566]]
validate rmse: 0.20104950857465576
[[ 404.56689453  416.14266968  390.74911499  364.59738159]
 [ 196.762146    230.66497803  218.86842346  203.6809082 ]
 [ 443.93676758  463.61575317  430.15350342

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00056: early stopping
[[1001.99976533 1063.26713459]
 [ 556.0001412   365.80809355]
 [ 461.00000027  459.19683789]
 [ 164.99997691  235.52132089]
 [ 311.99997159  297.31391469]
 [1631.00024893 1075.42744594]
 [1131.00006436  995.49547442]
 [ 182.00003656  196.11731783]
 [1283.99969223 1077.84915299]
 [ 140.99998243  132.33262144]
 [ 650.99994295  541.83505937]
 [ 860.99981585  803.71124431]
 [ 680.99984896  625.77382606]
 [1262.99983346 1326.7371733 ]
 [ 388.999972    361.20421521]
 [ 272.99995068  309.09868397]
 [ 705.00013454  911.57096309]
 [ 425.00003076  373.06902176]
 [ 140.99998243  118.72197732]
 [ 451.99991752  408.31741331]
 [ 260.99994013  334.32382677]
 [  74.00000482  125.24454609]
 [ 856.00012144  761.51706123]
 [ 150.9999799   110.37214058]
 [1244.00006883 1071.7472152 ]
 [1111.99972946  693.12855333]
 [ 426.99989052  370.90479738]
 [ 737.99999366  736.28560814]
 [1590.00008955 1

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00057: early stopping
[[ 755.99996772  391.99772516]
 [ 104.99998589   98.17508626]
 [ 909.99994715  555.91647447]
 [ 453.000062    368.12966546]
 [ 243.99994048  128.43148857]
 [  68.9999904    68.32775963]
 [ 414.99992771  388.47613727]
 [ 777.0000875   308.06745599]
 [  21.00000262   20.15582583]
 [ 201.00004069  113.57186674]
 [ 362.9999884   226.70488363]
 [  44.99999972   21.55663348]
 [ 515.99992695  352.81178475]
 [  66.99999548   56.27969293]
 [ 169.9999718   138.16349562]
 [ 532.99996301  425.54818278]
 [ 229.00005252  100.18255735]
 [ 136.00003364   93.33503434]
 [ 325.00001247  298.06524817]
 [  21.00000262   23.93339689]
 [ 134.99999684   69.58408468]
 [  82.00000212   81.20748584]
 [  65.00000066   78.48084548]
 [ 112.9999944   141.86117066]
 [2477.99970042  364.34357116]
 [  26.99999861   40.84511943]
 [  76.00000245   46.94504877]
 [ 314.99995226  187.43226793]
 [ 133.00000263  

Epoch 00042: early stopping
[[ 644.00011222  627.19882938]
 [ 239.99993885  286.58358543]
 [ 879.99991082  667.14807263]
 [ 252.00006595  211.1190192 ]
 [ 157.00002479  133.17796751]
 [ 355.00009949  271.79315565]
 [ 507.00011852  460.47388773]
 [ 317.9999176   155.50970859]
 [ 207.99994095  176.62345915]
 [ 501.00013178  474.16473225]
 [ 199.00001997  104.93369458]
 [ 118.00000492   93.65539937]
 [1856.99967752 1664.14902268]
 [ 472.0000925   336.51555081]
 [1397.00031787  983.14905031]
 [ 909.99994715  913.85567091]
 [ 459.00011542  299.69013204]
 [ 220.99999952  167.4256741 ]
 [ 488.99994471  567.12739693]
 [ 308.99998517  350.52741298]
 [ 315.99992899  195.88697448]
 [ 121.99999587  222.20502232]
 [ 888.00017958  724.15752489]
 [ 109.99999498  111.68472123]
 [ 104.99998589   98.27017949]]
validate rmse: 0.7336624994164296
[[1342.09155273  784.7668457   909.66296387  902.046875  ]
 [ 343.70654297  230.21864319  181.53388977  161.78077698]
 [ 832.3480835   568.92541504  611.48248291 

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00054: early stopping
[[243.99994048 319.47683061]
 [ 29.00000267  19.77808648]
 [ 39.9999989   25.66370375]
 [102.99999683 145.02125721]
 [ 25.00000141  28.9655257 ]
 [217.99998923 209.09011854]
 [142.00000596 128.85984703]
 [ 56.99999206  51.31376306]
 [302.99993598 268.638391  ]
 [ 12.00000164  20.37927132]
 [310.99996922 238.66372833]
 [ 36.99999956  41.07004863]
 [371.00004081 266.84858921]
 [301.00004527 265.2214871 ]
 [756.99981739 550.90045625]
 [ 63.00000677  50.12647543]
 [181.00005018 221.74194228]
 [ 29.00000267  25.77104349]
 [ 36.99999956  56.0532005 ]
 [ 26.99999861  36.01657133]
 [ 50.99999993  49.73681121]
 [ 38.99999862  51.75216875]
 [ 36.99999956  53.91916899]
 [ 21.99999838  18.1212921 ]
 [295.00008259 278.29130069]
 [375.0000253  276.50547184]
 [848.00023469 710.9547842 ]
 [ 31.00000232  30.25357443]
 [230.00006226 218.10093807]]
validate rmse: 0.6721376890411541
9 car:7aa

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00051: early stopping
[[162.00000134 120.62631046]
 [ 17.00000027  22.21328341]
 [317.9999176  240.30327205]
 [ 83.00000704  78.93218316]
 [371.00004081 200.9431304 ]
 [  5.00000014  10.00312768]
 [179.99997496  91.41750396]
 [229.00005252 139.90257608]
 [ 45.99999794  35.80943399]
 [ 23.99999825  36.37842526]
 [160.00002029 118.26776181]
 [118.9999846   68.26273869]
 [ 99.99999236  93.53551326]
 [ 31.00000232  26.09762269]
 [ 41.99999641  27.79284918]
 [ 96.99999242  83.74892547]
 [ 50.99999993  54.2778995 ]
 [ 29.00000267  30.60318007]
 [ 48.99999983  35.35818564]
 [ 26.00000154  51.88044693]
 [ 21.99999838  22.59823286]
 [110.99999676  76.51552743]
 [ 99.00001008 106.38540993]
 [ 33.00000393  56.41042814]
 [ 25.00000141  21.05399019]
 [ 63.00000677  49.44389314]
 [ 26.99999861  18.21142627]
 [ 80.00000397  61.95070589]
 [ 34.9999959   30.6327082 ]
 [110.99999676  83.65310744]
 [ 16.00000034 

Epoch 00050: early stopping
[[ 86.00000737  99.13319195]
 [ 44.99999972  40.95463016]
 [ 56.99999206  53.23468269]
 [ 65.99999399  76.16320285]
 [ 41.99999641  59.83055092]
 [ 85.00000375 130.14581374]
 [ 74.00000482  57.84619976]
 [ 91.00001126  54.41920516]
 [ 68.9999904   61.03048389]
 [ 76.00000245  86.04630558]
 [ 28.00000025  23.244029  ]
 [ 43.00000037  35.17669007]
 [136.00003364 100.42940901]
 [ 76.9999993   54.58860542]
 [ 76.00000245  92.78361849]
 [ 78.99999275  74.51003037]
 [106.99999041  65.6721318 ]
 [ 52.99999831  63.99526923]
 [124.00002842 157.58665512]
 [ 99.99999236 115.15744043]
 [ 60.99999323  55.84129783]
 [  1.           7.19680556]
 [ 90.00000639  96.12959559]
 [ 60.99999323  76.21878261]
 [ 54.00000138  38.81236982]]
validate rmse: 0.714654558793824
[[100.28463745  81.15866852  66.04529572  54.56190491]
 [ 52.62664413  60.58366394  39.83809662  27.92224121]
 [ 92.94696045  70.08067322  52.9142189   31.7990551 ]
 [ 34.4138298   29.99346161  23.12045479  28.135

Epoch 00058: early stopping
[[ 713.99995038  737.2797117 ]
 [ 287.00002598  292.58676036]
 [ 527.00004788  442.28498033]
 [ 217.00004704  514.44358038]
 [ 351.00007632  275.81418739]
 [1812.99997186 1160.91159299]
 [1447.99990484 1237.46846965]
 [ 356.00005067  362.12865209]
 [1860.00044686 1336.55830859]
 [ 157.00002479  187.01512038]
 [1729.0000029  1429.28507442]
 [ 819.99987211  735.53657969]
 [1675.99991064 1352.91305315]
 [2048.00056167 1900.8406917 ]
 [ 679.99999212  731.6759194 ]
 [ 432.9998972   429.5605097 ]
 [ 481.99992506  616.2266274 ]
 [ 413.00004393  365.30352907]
 [ 398.00007065  405.27865288]
 [ 497.00005302  449.28076176]
 [ 356.00005067  384.19534193]
 [ 335.00008305  417.56125241]
 [ 819.00007314  710.67592384]
 [ 214.99994616  179.56326606]
 [1738.9997924  1829.23646461]
 [2662.00052873 1852.43790319]
 [ 896.00009632  939.71557079]
 [ 801.9998996   812.27064347]
 [1915.99973462 1251.06978443]]
validate rmse: 0.6986779780556839
14 car:7a7885e2d7c00bcf
train shape: (

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00054: early stopping
[[ 425.00003076  327.38607041]
 [ 304.00005671  266.52965929]
 [ 483.99992854  340.9433729 ]
 [ 475.99987513  453.23404234]
 [  48.0000002    43.56494975]
 [ 225.00000496  193.76179252]
 [ 705.99984761  531.79111884]
 [ 839.99984033  736.12660835]
 [  76.00000245   77.4937701 ]
 [ 281.99998662  305.67414876]
 [ 513.00005822  352.77956444]
 [  65.00000066   69.3097427 ]
 [ 455.99991107  318.81103403]
 [ 425.99988821  265.82727799]
 [ 780.00011482  751.11928638]
 [ 569.99998068  464.84808896]
 [ 661.00007268  496.21932606]
 [ 160.00002029  177.65619752]
 [ 227.00001875  185.28873142]
 [ 109.99999498  108.33875315]
 [ 178.0000116   113.49009162]
 [  50.00000668   51.29228081]
 [  36.99999956   46.80975887]
 [ 169.9999718   204.8961067 ]
 [ 521.99992053  373.20940701]
 [ 115.99999528   71.86005587]
 [ 614.00002669  466.29108613]
 [ 436.0000121   215.60183483]
 [ 106.0000048   

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00036: early stopping
[[ 932.00015386  694.33553368]
 [ 967.00018177  769.58819788]
 [2048.00056167 1155.94444064]
 [ 501.99998152  562.89478532]
 [ 425.99988821  464.4064047 ]
 [1084.00015253  954.76638164]
 [1188.99970719 1008.11564465]
 [ 809.99979695  530.55301703]
 [ 995.99993493  722.23837812]
 [ 611.00009881  651.25725758]
 [ 551.99989244  394.34640588]
 [ 368.00006871  298.94363157]
 [2438.99988288 1029.43109078]
 [ 473.99998489  406.77825564]
 [3059.99962308 1923.29584585]
 [ 764.99978773  813.38462531]
 [1043.00015698 1139.49530391]
 [ 353.99990699  295.17856323]
 [ 784.99992067  792.14471406]
 [ 291.99998039  332.43916692]
 [1422.99962042  851.49299227]
 [ 287.00002598  494.04281701]
 [ 650.00007508  654.00277384]
 [ 542.00003445  410.97934423]
 [ 461.00000027  268.854658  ]]
validate rmse: 0.5222946168525504
[[1687.13513184  706.81878662  544.20703125  620.6907959 ]
 [ 482.31176758  

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00044: early stopping
[[1105.99982303  442.13308722]
 [ 210.99997023  196.51548315]
 [1000.99997273 1197.73313374]
 [ 149.00000129  261.13444996]
 [ 555.00015884  606.81985847]
 [1001.99976533  754.25113296]
 [2155.00023016 2427.45966856]
 [ 602.00013698  949.85596408]
 [1575.0002581  1749.52865913]
 [ 403.0000229   506.79892722]
 [2339.99963214 1437.18569487]
 [ 905.00001653 1039.56225352]
 [1096.9998011  1742.97183196]
 [ 820.99994843 1147.77676504]
 [1038.00017476 1679.82805253]
 [ 753.00011748 1072.97666603]
 [ 268.00002326  588.36461645]
 [ 980.00017544 1060.00777047]
 [ 103.99999232  126.07017275]
 [ 684.99983495 1080.8982367 ]
 [ 455.99991107  580.21208029]
 [ 126.00002325  219.52594902]
 [ 691.99998307  828.00855913]
 [ 469.99999906  358.05735593]
 [1343.00028379 1473.92867432]
 [4324.00091771 2810.15691762]
 [1078.00022623 1257.48753117]
 [1162.99994798 2058.9593156 ]
 [1049.99996959 1

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00036: early stopping
[[1215.999716    680.80703355]
 [ 348.0000798   322.22316382]
 [ 830.99978147  698.3769433 ]
 [ 654.00014427  505.84849868]
 [ 676.00007983  401.11210605]
 [  44.99999972   35.86560998]
 [1232.99997975  900.24729661]
 [2366.99951902  881.99826143]
 [ 205.00005415  161.4241996 ]
 [ 642.99991522  359.10799512]
 [ 822.99997984  515.05354353]
 [ 328.00005909  164.92351132]
 [ 535.00012083  345.83524858]
 [ 252.00006595  133.15731505]
 [ 510.99995931  363.18331032]
 [ 880.99978462  726.02839   ]
 [ 617.00015321  508.27988423]
 [ 370.00003455  225.5806459 ]
 [ 856.99979978  598.27069152]
 [ 250.9999714   264.96324186]
 [ 291.99998039  171.60589048]
 [ 291.99998039  207.84074339]
 [ 212.00002596  203.27664045]
 [ 340.99997407  372.97581799]
 [ 657.99988447  285.41968173]
 [ 326.00008753  239.79820495]
 [ 861.99988667  448.96654997]
 [ 816.00001641  522.29353978]
 [  80.00000397  

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00063: early stopping
[[ 319.00007288  314.61100392]
 [ 145.00001747  117.37468361]
 [ 529.99988676  395.67144478]
 [ 778.00000401  612.32005782]
 [ 197.99997857  179.10436513]
 [ 678.00000702  574.40346315]
 [ 430.99991008  328.87653911]
 [ 541.00006062  421.22526688]
 [1016.00003614  695.84471712]
 [ 450.99990877  482.32700466]
 [  93.00000537   91.39148916]
 [ 126.99997512  126.5722738 ]
 [ 379.99991384  322.80002738]
 [  54.99999325   54.86455325]
 [ 596.00009713  542.47999269]
 [ 114.99998923  117.76163216]
 [ 256.9999509   231.23503189]
 [  61.99999162   75.45041061]
 [ 503.00009315  396.84772624]
 [ 497.99992904  319.29777961]
 [ 609.00013207  378.42553334]
 [  58.99999791   85.26802662]
 [ 843.00000192  510.42206199]
 [ 786.00019964  763.09994196]
 [  69.9999972    48.16519901]]
validate rmse: 0.6876398084589097
[[302.84432983 277.28482056 262.74481201 233.4934082 ]
 [104.15361023  89.96

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00064: early stopping
[[139.00001385 154.48320901]
 [ 26.00000154  27.20320897]
 [ 61.99999162  81.29165373]
 [ 37.99999829  87.30151039]
 [ 38.99999862  32.9978147 ]
 [102.00000774 110.59244285]
 [102.00000774 118.70230524]
 [ 61.99999162  73.52636261]
 [152.00001663 179.98219263]
 [ 25.00000141  28.25119503]
 [299.9999719  274.64716414]
 [184.00002016 123.71506554]
 [386.00008907 311.96072692]
 [339.99996983 347.81742932]
 [202.00003439 208.24727908]
 [ 88.99999894 100.23254693]
 [168.99999388 109.30371717]
 [ 68.9999904   58.33222346]
 [ 45.99999794  40.53631215]
 [ 60.99999323  67.79829952]
 [ 88.00000708  78.4633343 ]
 [ 16.00000034  28.39314985]
 [ 94.99999109  83.06014653]
 [ 31.00000232  25.2213487 ]
 [217.99998923 176.97726943]
 [567.00004138 347.36261907]
 [231.00006026 191.68487852]
 [154.00001047 179.37266159]
 [118.00000492 100.9480135 ]]
validate rmse: 0.6511471140824789
24 car:b4

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00059: early stopping
[[ 118.9999846   118.73871991]
 [ 154.00001047  166.21126449]
 [ 145.00001747  210.25024787]
 [ 275.99992493  258.83963718]
 [  75.00000294   72.28716387]
 [1184.00010247 1083.95407798]
 [ 909.00005335  827.07642774]
 [ 950.00001097  906.243774  ]
 [ 322.99996572  138.28369918]
 [ 353.00009933  214.64926109]
 [ 684.99983495  531.91026049]
 [  94.99999109  113.52060368]
 [ 308.00004471  309.89475016]
 [ 186.99997475  177.09034538]
 [ 753.99989752  730.13599305]
 [ 253.99996984  318.65120783]
 [ 356.99994765  347.95730621]
 [ 102.99999683   68.83183412]
 [ 433.99987828  441.12880888]
 [ 413.00004393  312.3639814 ]
 [ 118.9999846    85.83606428]
 [ 186.99997475  186.84450754]
 [ 130.9999878   111.95952858]
 [ 186.99997475  164.48615112]
 [ 207.99994095  208.24608292]
 [ 324.00002768  313.0348335 ]
 [ 368.00006871  347.25589081]
 [  96.99999242   97.63595057]
 [1462.99980806 1

Epoch 00053: early stopping
[[1650.00041682 1288.7447964 ]
 [ 185.99997167  200.79394727]
 [ 274.99997401  286.19355684]
 [ 223.99998952  186.41678223]
 [ 234.9999814   212.23980752]
 [ 640.00017989  501.29460809]
 [ 585.99999502  470.62268004]
 [ 483.99992854  364.22744124]
 [ 166.00002688  174.66331942]
 [ 538.00007009  484.77145418]
 [  76.00000245   63.65544229]
 [  78.00000326   79.89681765]
 [2058.99952617 1496.33874368]
 [ 138.00003108  156.148072  ]
 [ 390.00002732  449.31973109]
 [ 325.00001247  339.15267165]
 [ 409.00001026  337.8491969 ]
 [ 201.00004069  161.08464219]
 [1394.00005822 1130.38956878]
 [1004.0000405   859.53125987]
 [ 436.99989339  390.53645988]
 [ 410.99988229  410.40563803]
 [ 919.00006615  602.97153775]
 [ 248.99994531  238.2667812 ]
 [  63.99999286   92.22158079]]
validate rmse: 0.6808292062158892
[[1226.11865234 1425.59387207 1882.74645996 1406.65014648]
 [ 324.49694824  364.25027466  391.88858032  326.79876709]
 [ 477.17306519  538.1484375   665.73937988 

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00056: early stopping
[[ 38.99999862  34.4829248 ]
 [118.9999846   78.95267865]
 [166.00002688 223.87843496]
 [ 87.00000653  95.51494231]
 [ 63.00000677  72.43902106]
 [360.99991187 251.16308367]
 [196.99998379 300.24286616]
 [ 44.99999972  49.94825193]
 [234.00000576 271.08032907]
 [ 58.99999791  87.49166794]
 [ 99.99999236  63.4559374 ]
 [371.99997203 317.78336019]
 [ 80.00000397  95.55357377]
 [132.00003608 152.14117149]
 [203.99997262 193.04914595]
 [ 45.99999794  70.43672095]
 [ 37.99999829  35.49104551]
 [178.99997609 180.85455741]
 [ 61.99999162  41.29522025]
 [199.9999427  222.72138652]
 [ 60.99999323  61.8286129 ]
 [ 50.99999993  69.10543555]
 [ 91.00001126  65.56934545]
 [ 88.99999894  53.16856905]
 [219.00001062 334.34917613]
 [294.00001659 244.15331485]
 [274.00002607 228.15649079]
 [287.99993575 368.28934572]
 [348.99995842 298.93367248]]
validate rmse: 0.6930333440235499
29 car:07

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00038: early stopping
[[473.99998489 298.86482652]
 [168.00001157 157.37037824]
 [453.000062   365.72447627]
 [304.00005671 428.06862264]
 [219.00001062 171.07729081]
 [240.99994394 308.24074057]
 [344.00008256 360.73044983]
 [368.99996836 324.68281511]
 [400.99991886 257.15041872]
 [331.00003959 276.51738381]
 [306.99998966 407.73828905]
 [457.99987729 361.64931185]
 [331.00003959 485.75202964]
 [324.00002768 276.50912479]
 [621.00007058 475.44544718]
 [302.99993598 345.99996484]
 [158.00004306 146.85838194]
 [383.00002067 285.31035261]
 [292.9999749  315.93550015]
 [804.9998076  724.75549344]
 [376.99991967 344.6535441 ]
 [176.00002774 190.64624319]
 [176.00002774 185.18531171]
 [322.99996572 320.18024571]
 [130.9999878  115.86162156]
 [691.99998307 710.88985671]
 [501.99998152 381.3527488 ]
 [261.99999581 150.18826363]
 [292.9999749  418.61429544]
 [329.99997927 366.89559501]
 [648.99987899 

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00052: early stopping
[[ 538.00007009  600.07926159]
 [ 962.99988057  597.19434133]
 [2086.00047489 1558.90665215]
 [1049.99996959 1409.44085173]
 [ 605.00000815  623.95984941]
 [3174.99955735 2055.98354982]
 [3096.00063644 2347.51567487]
 [3148.0002658  2430.08658652]
 [1333.00011128  818.66284566]
 [2375.99938611 3152.94411868]
 [1027.99996223  660.84062886]
 [ 672.00014998 1089.92328379]
 [ 978.99984048  688.52442999]
 [ 425.00003076  381.36742519]
 [2931.99926888 2314.00675468]
 [ 479.00013488  390.61655086]
 [1283.99969223 1002.77128827]
 [ 295.99997994  238.76793706]
 [2005.00022674 1456.42052107]
 [ 421.99997302  447.90301138]
 [3648.00013288 2523.72004953]
 [ 277.00001148  345.53244697]
 [ 625.99995481  620.41643005]
 [ 764.99978773  816.52607275]
 [ 742.99982408  748.3300554 ]]
validate rmse: 0.6443093617649569
[[ 751.13476562  757.3380127   631.04223633  672.22589111]
 [ 574.25830078  

Epoch 00034: early stopping
[[ 375.0000253   419.04636503]
 [ 172.00002801  126.70742669]
 [ 451.99991752  407.75374668]
 [ 505.99990097  625.77921769]
 [ 201.00004069  131.26067151]
 [ 790.00001073  482.30013201]
 [ 591.00011094  439.72604421]
 [ 327.00004691  328.80004171]
 [ 726.99987536  553.7929472 ]
 [ 101.00000941  115.63583761]
 [1108.00021688  586.14643188]
 [ 353.00009933  282.83866204]
 [1009.99991042  627.68644891]
 [ 803.00016217  672.9924962 ]
 [2147.9993906  1313.77486812]
 [ 481.99992506  450.32170488]
 [ 438.00005504  356.40065558]
 [ 386.99998998  383.45831925]
 [ 448.0000136   333.75857496]
 [ 436.99989339  400.45762458]
 [ 433.99987828  316.59038162]
 [ 571.00009438  445.06250704]
 [ 315.99992899  244.98931109]
 [ 103.99999232   90.07114149]
 [ 846.00018827  532.10185956]
 [1515.00015777  989.3606812 ]
 [2376.99996425 1329.04901568]
 [ 331.00003959  317.18011565]
 [ 799.99989425  536.76107832]]
validate rmse: 0.5204035688506286
34 car:97f15de12cfabbd5
train shape: (

36 car:b25c4e2e3856af22
train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00045: early stopping
[[1560.99976974  812.90541667]
 [ 461.00000027  477.34120237]
 [1320.00012077  935.35147038]
 [ 616.00013695  789.73550674]
 [ 429.9999255   239.91779173]
 [ 612.0000831   520.70714409]
 [ 571.00009438  567.55038344]
 [ 283.00003144  426.45452262]
 [ 280.99992477  249.42709451]
 [ 207.99994095  287.79471623]
 [ 644.00011222  610.36975931]
 [ 352.00008264  353.39408061]
 [ 679.99999212  691.56686538]
 [ 533.99987225  379.1171681 ]
 [1368.99996712 1153.90520812]
 [ 542.00003445  662.2895625 ]
 [ 574.00009625  614.66836122]
 [ 236.99997416  137.77446527]
 [ 205.00005415  227.70402593]
 [ 265.00007515  206.74199798]
 [ 196.99998379  125.23929461]
 [ 140.99998243  160.87797943]
 [ 177.00004151  245.68898405]
 [ 438.99998416  455.99362495]
 [ 166.99999884  174.36861159]
 [ 212.00002596  263.39332162]
 [ 234.00000576  373.87411323]
 [1144.00007135  643.849

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00063: early stopping
[[ 561.99989291  512.52645767]
 [ 182.00003656  136.59525971]
 [ 726.0000328   530.69108495]
 [ 356.00005067  292.54861326]
 [ 139.00001385  118.89521176]
 [ 291.99998039  279.95693286]
 [ 809.99979695  796.7055438 ]
 [ 381.99992236  317.61620431]
 [ 102.99999683   74.78293855]
 [ 809.99979695  751.7567904 ]
 [ 197.99997857  183.94433082]
 [ 217.00004704  199.09445769]
 [1009.00024915  779.49266565]
 [ 373.00002731  260.99049555]
 [ 917.00004467  804.9803876 ]
 [ 674.99980939  510.0319846 ]
 [ 386.99998998  295.38209164]
 [ 291.00005581  239.82768279]
 [ 482.99986261  571.28255376]
 [ 236.00002804  286.35404414]
 [ 466.00004098  408.03630297]
 [ 213.99999734  290.24902576]
 [ 578.000063    678.76568587]
 [  83.99999931   69.46737436]
 [ 164.00001689  111.46272329]]
validate rmse: 0.7875732433538765
[[ 744.91235352  709.66998291  691.23339844  814.96331787]
 [ 223.79190063  

Epoch 00058: early stopping
[[  75.00000294   62.7841073 ]
 [ 138.00003108  147.5877443 ]
 [ 870.99992542  832.74526427]
 [  69.9999972   197.65874224]
 [ 647.00001368  471.93963803]
 [ 784.99992067  589.19758284]
 [1542.0002407  1411.1849411 ]
 [ 403.0000229   310.95888559]
 [1389.9998858  1066.38031633]
 [ 154.00001047  188.29347341]
 [1259.00019799 1059.466631  ]
 [ 707.00016612  681.45413912]
 [ 905.00001653  943.5069599 ]
 [2086.00047489 1871.52742282]
 [ 673.99985762  552.14195583]
 [ 856.99979978  686.51790652]
 [  36.00000432   44.10910102]
 [ 736.0001942   514.08970167]
 [  90.00000639   75.70958379]
 [ 499.00009691  530.62494197]
 [ 433.99987828  379.33935075]
 [  74.00000482  120.59870278]
 [1419.99980144 1131.7025419 ]
 [ 322.99996572  187.99606738]
 [1268.9997982  1164.9501935 ]
 [2027.00041062 1823.78306613]
 [ 541.00006062  552.46744412]
 [ 761.00021783  866.78266341]
 [ 816.99990726  583.24004549]]
validate rmse: 0.8027398285365965
39 car:283d331fdf05a655
train shape: (

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00043: early stopping
[[ 673.99985762  478.88706798]
 [ 450.99990877  341.73213029]
 [ 438.00005504  350.29775867]
 [ 426.99989052  421.22671857]
 [ 176.00002774  158.96798478]
 [ 161.00000321  106.16062102]
 [ 853.99984693  621.86566645]
 [ 750.00010847  664.72487841]
 [ 233.00000251  140.90549944]
 [ 450.00004463  372.88263751]
 [ 438.99998416  389.20983775]
 [ 287.99993575  218.30836792]
 [ 290.00005731  324.16793645]
 [ 676.00007983  334.29444696]
 [1437.99987795  839.09324836]
 [ 370.00003455  513.43723071]
 [ 328.99991685  324.73466502]
 [ 442.99993346  203.50363317]
 [ 344.00008256  277.80355091]
 [ 596.00009713  574.71401443]
 [ 433.99987828  251.34564694]
 [ 203.99997262  129.55070939]
 [ 147.99997855  115.04336265]
 [ 332.00007938  261.12455055]
 [ 213.99999734  159.09824636]
 [ 645.99998127  512.80355515]
 [ 830.99978147  580.47742376]
 [ 351.00007632  301.14963433]
 [ 164.00001689  

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00032: early stopping
[[277.00001148 228.28613758]
 [277.00001148 196.59552935]
 [124.99997469 105.50073446]
 [ 78.00000326  77.63892563]
 [227.99993794 176.25932047]
 [223.00006356 202.21003713]
 [158.00004306 117.13309983]
 [137.00000247  75.1678127 ]
 [ 78.00000326  78.86257454]
 [163.00003119 152.62169354]
 [ 28.00000025  28.00536445]
 [ 45.99999794  20.36597797]
 [353.99990699 292.75722267]
 [ 85.00000375  68.10220738]
 [152.99999717 117.00809222]
 [168.99999388 142.28110812]
 [373.00002731 248.36159129]
 [ 82.00000212  61.8849992 ]
 [409.99990442 402.35216741]
 [185.000003   161.04162338]
 [130.9999878   84.20552582]
 [ 66.99999548  59.46834879]
 [213.00005002 200.39977475]
 [ 87.00000653  95.42262487]
 [ 86.00000737  85.69327654]]
validate rmse: 0.7519608200367508
[[288.1697998  231.24282837 284.76901245 243.97341919]
 [ 97.88854218  79.91389465  95.6437912   85.04077148]
 [206.86802673 1

Epoch 00028: early stopping
[[ 497.00005302  636.33167591]
 [ 439.99992146  388.48238519]
 [1178.00003536  824.8035103 ]
 [ 423.0000615   882.5496295 ]
 [ 589.9998718   364.63332495]
 [3260.00028255 1563.67760084]
 [3302.99923193 2108.83614895]
 [ 541.00006062  498.86253719]
 [2082.99998463 1328.51398232]
 [ 223.99998952  238.026715  ]
 [1452.99967625 1068.3207104 ]
 [2474.99968086 1797.50426695]
 [1416.99979504 1019.68561519]
 [2484.99962157 1998.89079225]
 [ 994.00018273  939.17164392]
 [ 938.00014208  815.84067232]
 [ 492.99991173  551.61099077]
 [ 998.00027081  623.87849831]
 [ 771.99979427  636.00572933]
 [ 564.99998794  486.8825073 ]
 [ 667.00017178  557.96449001]
 [1078.00022623  804.45807309]
 [1638.00027265 1048.59565663]
 [ 274.00002607  206.24739807]
 [1856.00049729 1449.16395055]
 [2896.99993475 1833.21242902]
 [1081.00006263  723.13833056]
 [2533.00006227 2233.91295626]
 [4173.00067725 1970.83587588]]
validate rmse: 0.5252458597269549
44 car:4a103c30d593fbbe
train shape: (

46 car:c6cd4e0e073f5ac2
train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00048: early stopping
[[ 890.99980412  545.52000438]
 [ 376.99991967  293.55908606]
 [ 630.99986246  655.16307242]
 [ 833.99989357  276.47132703]
 [ 339.99996983  238.17127289]
 [ 233.00000251  136.44595469]
 [1188.99970719  720.91705028]
 [1763.99969863  857.54489918]
 [  33.00000393   42.07134488]
 [ 124.00002842   79.30371654]
 [ 557.00000567  402.40347673]
 [  60.99999323   88.60507346]
 [ 230.00006226  219.16523797]
 [ 120.99999821   77.87031786]
 [ 341.99997286  261.46824944]
 [ 297.00002512  476.45614336]
 [ 551.00014181  437.77569937]
 [ 136.00003364  101.64018057]
 [ 270.99999632  129.4768383 ]
 [  52.00000708   64.40608973]
 [ 136.00003364   72.63384383]
 [ 110.99999676   93.67261536]
 [  63.99999286  107.25523071]
 [  61.99999162   81.16964222]
 [ 122.99999157   71.13589038]
 [ 101.00000941   81.43809917]
 [ 542.00003445  300.47888068]
 [1240.99974492  514.567

Epoch 00030: early stopping
[[ 490.00004992  378.86334225]
 [ 394.99997489  254.67212445]
 [1250.00023759  806.2580185 ]
 [1344.99972315  731.75367342]
 [ 327.00004691  243.37063046]
 [ 421.99997302  368.26353839]
 [1243.00010771  715.80469035]
 [ 922.00007167  587.23525021]
 [ 637.99982851  284.11489895]
 [1228.00014812  900.44226288]
 [ 391.99997677  203.95088171]
 [ 416.99991462  267.0523708 ]
 [ 694.99988928  458.59585976]
 [ 292.9999749   197.92618166]
 [1739.99994841 1115.07880701]
 [ 393.0000695   309.79010299]
 [ 436.99989339  322.91741587]
 [ 256.00001096  214.21693836]
 [1273.99970486 1003.8587612 ]
 [ 350.00009641  320.18042962]
 [ 578.99991269  435.18885591]
 [  33.00000393   94.02243391]
 [1066.9997555   629.58430433]
 [ 410.99988229  292.66676778]
 [ 155.99997376   67.74621396]]
validate rmse: 0.5691692535548629
[[ 596.03668213  452.0194397   338.20861816  233.7865448 ]
 [ 293.70092773  238.54238892  210.45126343  123.0868988 ]
 [ 394.20016479  276.01385498  262.27404785 

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00040: early stopping
[[ 375.99993867  529.15637896]
 [ 566.00010654  520.85312078]
 [2245.99939361 2288.42879238]
 [ 414.99992771  987.33002317]
 [ 959.99990354 1387.57245696]
 [3049.00077407 2483.26597585]
 [4187.99887239 4349.04654287]
 [ 740.00012619  741.6515893 ]
 [3248.99909498 3417.79376981]
 [ 538.00007009  835.88322207]
 [2275.00040995 2728.64764894]
 [1860.00044686 2774.09486469]
 [1890.00036963 2761.13565922]
 [2563.99943877 3478.5672574 ]
 [2038.00013833 2290.30134616]
 [1849.00003162 1925.9357465 ]
 [ 234.9999814   239.1268451 ]
 [1639.99987074 1643.92046335]
 [ 778.00000401  819.17320896]
 [1156.99996521 1878.61317904]
 [1027.99996223 1452.59996114]
 [1021.99999747 1269.22796593]
 [1685.00004555 2261.50663165]
 [ 574.00009625  654.6018417 ]
 [2002.00009992 2543.00646943]
 [4335.99878861 4631.23152701]
 [1364.00010674 1839.08483363]
 [2496.00035039 2815.79913365]
 [2481.00050625 2

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00042: early stopping
[[ 952.99993968  463.4532128 ]
 [ 316.99998477  175.4379391 ]
 [ 364.0001012   279.78540611]
 [  63.99999286  104.46119505]
 [ 373.99997834  245.18597609]
 [ 175.0000347   211.80211815]
 [1295.0002047   761.32331316]
 [1705.00040815 1384.01994706]
 [ 607.00008723  246.65814126]
 [ 555.00015884  309.78405304]
 [ 919.00006615  881.56470661]
 [ 629.99995312  461.78552191]
 [ 295.99997994  406.92034004]
 [ 612.0000831   419.91015418]
 [ 650.00007508  290.52724308]
 [ 528.99987104  240.17383613]
 [ 621.99998643  347.60732008]
 [ 306.00001794   98.91210751]
 [ 433.99987828  323.61576608]
 [ 270.99999632  340.82197647]
 [ 297.00002512  255.06079927]
 [ 393.0000695   296.11255483]
 [ 398.99988643  273.87131641]
 [ 388.999972    170.49272692]
 [ 322.00003127  233.87154697]
 [ 730.00012491  528.45625203]
 [2055.00005965 1039.53120388]
 [ 413.99996722  256.3774585 ]
 [ 410.99988229  

Epoch 00033: early stopping
[[1178.9998496   907.22291825]
 [ 379.00003007  252.39394087]
 [1224.99971305 1091.53466025]
 [ 509.00005687  422.49814393]
 [ 154.00001047  161.42633219]
 [ 284.99996835  308.19400254]
 [ 807.99979814  618.25423239]
 [ 843.00000192  562.23462399]
 [ 310.99996922  324.8245827 ]
 [ 542.99998524  613.79021947]
 [ 185.99997167  143.77647551]
 [ 116.99999385  107.4925245 ]
 [3318.00036489 2239.67141861]
 [ 630.99986246  357.58771805]
 [2375.00059334 1866.19875992]
 [ 888.99995196  694.84621304]
 [ 368.00006871  295.77122097]
 [ 289.0000092   215.26117211]
 [ 459.99989579  547.17885241]
 [ 581.00013167  574.07857063]
 [1013.0001857   587.34353475]
 [ 202.99998922  469.26950267]
 [ 574.00009625  476.39374996]
 [ 234.9999814   212.74156801]
 [ 233.00000251  160.89812547]]
validate rmse: 0.5949937555326555
[[2488.40380859  968.60424805  562.64593506  583.63201904]
 [ 550.52301025  264.81314087  136.40159607  104.02397919]
 [ 864.93548584  400.53521729  240.74304199 

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00083: early stopping
[[  32.00000315   59.36198994]
 [  74.00000482   81.89995164]
 [ 358.99992633  386.8537507 ]
 [  86.00000737  249.37666884]
 [ 122.99999157   93.89533613]
 [ 184.00002016  126.11935134]
 [ 425.00003076  429.35749344]
 [ 138.00003108  170.45375529]
 [ 181.00005018  196.24961171]
 [  65.99999399   84.43063637]
 [ 292.9999749   244.37653867]
 [ 287.00002598  192.21873681]
 [ 292.9999749   272.34136319]
 [ 345.99996484  378.17108445]
 [ 491.9999009   582.87499985]
 [ 243.00004887  313.74605007]
 [  48.0000002    51.44300814]
 [ 299.9999719   216.62880314]
 [  60.99999323   73.27815658]
 [ 133.00000263  169.82790758]
 [  99.99999236  111.55005343]
 [ 112.9999944    85.50680667]
 [ 140.99998243  166.81305242]
 [ 102.99999683   63.57373933]
 [ 187.99995483  230.10577492]
 [1101.99973566  610.39605429]
 [ 467.00004659  431.62496538]
 [ 393.0000695   390.66008057]
 [ 217.00004704  

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00035: early stopping
[[2769.99961116 1310.7485464 ]
 [1040.99991136  627.0885999 ]
 [1384.99969873  768.95633133]
 [1020.00018486  731.78309601]
 [ 831.99989217  547.30112713]
 [ 284.99996835  146.40651689]
 [2676.99964725 1967.45625722]
 [3490.99940424 1609.14455169]
 [ 505.99990097  355.63155686]
 [ 644.00011222  357.94919211]
 [2840.99997059 1386.04781391]
 [ 740.00012619  427.33480966]
 [ 837.99989067  541.73983247]
 [ 426.99989052  161.10277829]
 [ 876.00017766  547.18608126]
 [ 933.00015955  703.88700428]
 [ 990.0002051   839.89466405]
 [ 718.9998835   395.91629136]
 [ 552.99986885  381.57689914]
 [ 371.99997203  273.31013877]
 [ 602.99993852  354.29527276]
 [ 640.00017989  418.12550735]
 [ 504.99991625  372.41280592]
 [ 638.99995553  405.94474425]
 [ 898.99989209  399.64991946]
 [ 292.9999749   234.63352028]
 [1786.99971436  842.56722621]
 [1291.00007699  739.9750486 ]
 [ 129.99997401  

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00070: early stopping
[[ 845.00023594  399.53951819]
 [ 140.0000052   106.48405187]
 [ 271.99993203  196.39056786]
 [  96.99999242  148.04044893]
 [  78.00000326   94.21340324]
 [ 192.00003043  163.96337699]
 [ 517.00001492  374.74443566]
 [ 163.00003119  112.85648014]
 [  88.99999894   57.28515165]
 [ 399.99991627  530.15120924]
 [  70.9999975    52.82417877]
 [  28.00000025   46.52584751]
 [1173.99980908  819.09040031]
 [ 188.99996277  142.1210983 ]
 [ 640.00017989  337.90761349]
 [ 459.99989579  378.04077557]
 [ 231.00006026  190.38590655]
 [ 169.9999718   122.94952225]
 [ 210.99997023  194.47975082]
 [ 308.99998517  421.48616858]
 [ 289.0000092   133.65854217]
 [  85.00000375   58.00104259]
 [ 627.99983535  595.80328505]
 [  54.99999325   45.28911336]
 [  50.99999993   56.07505014]]
validate rmse: 0.5120642299309665
[[1038.45544434  585.86199951  336.6265564   403.42816162]
 [ 278.97775269  

Epoch 00056: early stopping
[[ 127.9999956   145.7948305 ]
 [ 206.99996764  130.62227425]
 [ 851.00013046 1140.22139599]
 [ 312.99995326  463.43511125]
 [ 340.99997407  364.37684764]
 [1168.00010177  816.57625804]
 [3240.99921699 4125.81243013]
 [ 319.00007288  340.8392043 ]
 [1693.99985947 1889.82451007]
 [1205.99997009 1796.18009053]
 [ 733.00012515  603.15824539]
 [ 447.00012455  523.61461586]
 [ 679.99999212  743.37035631]
 [1387.00032021 1191.13380041]
 [2551.00019306 2203.58697625]
 [ 450.00004463  720.63552417]
 [  83.99999931  130.97094626]
 [ 856.00012144  855.66043753]
 [ 469.00003486  379.32170207]
 [ 807.99979814 1016.71342551]
 [ 406.00000976  587.69483791]
 [ 605.99991871  724.28440111]
 [1031.99993353  934.70161223]
 [1325.99969575 1211.26500412]
 [1729.0000029  1812.21182247]
 [2646.00005818 1876.05215258]
 [3262.99956907 2725.55395373]
 [ 423.0000615   698.09299182]
 [1268.9997982  1144.55020118]]
validate rmse: 0.7074825818629709
59 car:79de4e4b24c35b04
train shape: (

train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00052: early stopping
[[335.00008305 289.9792363 ]
 [149.00000129 172.65649029]
 [299.9999719  340.95159809]
 [234.9999814  262.00932642]
 [342.99994894 225.87042525]
 [ 31.00000232  36.08219027]
 [348.0000798  349.03083112]
 [406.00000976 397.82339549]
 [766.9999589  460.86947469]
 [154.99997147 152.59697405]
 [403.0000229  335.85610479]
 [486.00013524 507.19119314]
 [229.00005252 266.30210746]
 [364.0001012  243.67500462]
 [332.00007938 300.56001035]
 [205.99995039 211.57486192]
 [134.99999684 114.05569796]
 [328.99991685 229.85887952]
 [118.00000492 100.00570773]
 [661.00007268 591.58462154]
 [239.99993885 193.23996431]
 [152.00001663 178.22283402]
 [168.00001157 221.88463929]
 [134.00000129 170.33826361]
 [ 73.0000048   92.24603035]
 [736.99983897 618.50997241]
 [322.00003127 192.45825292]
 [232.00000846 141.8011296 ]
 [ 63.00000677  80.00172717]
 [272.99995068 277.9143135 ]
 [283.00003144 

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00039: early stopping
[[1847.00020598 1480.85156347]
 [ 571.99999155  470.48888944]
 [ 860.99981585  818.60077708]
 [ 486.00013524  520.8665838 ]
 [ 368.99996836  414.6687213 ]
 [ 806.00010798  911.32856845]
 [1501.99969111 1000.62516407]
 [ 992.99981647  594.26150481]
 [ 429.9999255   374.02941026]
 [1229.0000429  1048.75347273]
 [ 451.99991752  356.11253464]
 [ 407.00005056  367.36120927]
 [2119.00036708 1764.10102448]
 [ 469.99999906  474.42572205]
 [1027.99996223  874.39704192]
 [ 556.0001412   428.49125246]
 [1006.00026391  698.40061113]
 [ 513.00005822  380.83636821]
 [8990.00245018 6283.0965504 ]
 [1205.00009977 1241.90393219]
 [1183.00012496  664.32256883]
 [ 260.99994013  381.81083072]
 [1634.99981112 1523.09985292]
 [ 353.99990699  285.291507  ]
 [ 257.99994357  221.09967059]]
validate rmse: 0.505628149721653
[[1861.43041992 1798.95153809 1920.50561523 1771.05566406]
 [1424.09631348 14

Epoch 00026: early stopping
[[ 29.00000267  69.70643615]
 [ 65.99999399  61.21592818]
 [281.99998662 178.22262928]
 [ 58.99999791 113.84824399]
 [ 90.00000639  67.70696216]
 [149.00000129  88.07682088]
 [257.99994357 109.76741095]
 [ 15.00000017  22.79795503]
 [208.99994294 165.85592135]
 [ 19.99999791  22.70281602]
 [108.00001109 105.79176748]
 [ 44.00000015  73.89657725]
 [150.9999799  139.54014472]
 [129.00003593 122.18197859]
 [ 26.00000154  22.37385446]
 [178.0000116  136.26831903]
 [ 10.99999992  27.12068417]
 [155.99997376  76.64262639]
 [ 34.00000316  40.20263942]
 [147.99997855 163.43757042]
 [118.9999846  101.75329911]
 [ 50.99999993  45.33581912]
 [ 88.00000708  93.76111241]
 [  2.00000001  27.78313677]
 [152.99999717 249.43783993]
 [453.000062   649.9164488 ]
 [ 63.00000677  57.76390656]
 [ 88.00000708  65.37443056]
 [ 91.00001126  96.28178131]]
validate rmse: 0.4717123266011287
64 car:17363f08d683d52b
train shape: (264, 1, 18)
label shape: (264, 1)
test shape: (22, 1, 18)


train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00044: early stopping
[[1261.99982229  654.89217718]
 [ 366.9999273   353.68650303]
 [1333.99968024  776.66141693]
 [ 558.99999466  579.60018642]
 [ 432.9998972   275.27068942]
 [  90.00000639  248.54368861]
 [ 569.99998068  481.82359911]
 [1069.99970961  515.57686007]
 [ 136.00003364  165.91976219]
 [  98.00000722   75.98385223]
 [ 803.00016217  632.35939523]
 [ 438.00005504  362.92639369]
 [ 574.99996238  474.72230222]
 [ 315.99992899  269.01654756]
 [ 712.99996652  599.19752554]
 [ 513.00005822  496.70638764]
 [ 205.99995039  181.73282067]
 [ 243.00004887  190.86000896]
 [ 134.99999684  138.15167146]
 [ 268.00002326  289.96707752]
 [ 238.00005591  168.5954925 ]
 [  71.99999351   76.9832165 ]
 [  92.00000298  136.69376173]
 [ 139.00001385  115.78461539]
 [ 186.99997475  113.28366642]
 [ 368.99996836  289.44689338]
 [ 356.00005067  238.81923543]
 [1372.99964098  780.13094961]
 [  88.99999894  

Epoch 00054: early stopping
[[457.99987729 287.50194067]
 [174.00002648 182.64000046]
 [591.00011094 506.19728599]
 [334.00002345 342.19391654]
 [187.99995483 198.13217675]
 [321.00005791 388.82170858]
 [431.99998693 414.80831996]
 [454.99993847 369.1364901 ]
 [225.99994133 217.10851385]
 [464.00005273 435.50117985]
 [ 87.00000653  80.06045296]
 [ 87.00000653  93.94812424]
 [829.99991946 606.13568598]
 [223.99998952 238.22312724]
 [766.9999589  516.48563706]
 [309.99996687 326.05701717]
 [194.99999862 152.64133173]
 [194.99999862 133.69616602]
 [393.99999799 310.56368849]
 [386.00008907 378.37749872]
 [454.99993847 422.7433219 ]
 [ 58.99999791  75.27768919]
 [709.99984595 687.68098471]
 [199.00001997 166.74503673]
 [ 39.9999989   40.56506617]]
validate rmse: 0.753813820292909
[[551.70446777 441.96035767 316.96817017 259.9942627 ]
 [267.38128662 227.43484497 159.30303955 140.59539795]
 [325.16107178 286.79016113 218.21328735 189.12173462]
 [197.58300781 145.02680969 119.81351471  89.105

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00046: early stopping
[[  50.00000668  119.94531338]
 [ 118.9999846   132.82280961]
 [ 903.99990479  984.652338  ]
 [  92.00000298  266.69780823]
 [ 283.00003144  256.17417105]
 [ 696.99997534  440.80611909]
 [1872.00047934 1905.77560697]
 [ 233.00000251  248.60165666]
 [ 551.00014181  748.65809191]
 [ 187.99995483  146.09838149]
 [ 425.99988821  456.96795777]
 [ 607.00008723  524.51918211]
 [ 360.99991187  442.0716336 ]
 [ 888.99995196  894.99656418]
 [ 794.00010886  824.68128888]
 [ 406.00000976  610.6018955 ]
 [  85.00000375  103.27217791]
 [ 665.99982918  534.82744586]
 [  93.00000537   65.58708693]
 [ 403.0000229   483.82981861]
 [ 243.00004887  247.32620962]
 [ 145.00001747  171.0512524 ]
 [1035.99999683  592.09964589]
 [ 223.99998952  149.64490341]
 [ 503.00009315  827.44326084]
 [1849.99969365 1181.18655274]
 [ 855.00013589  513.26591378]
 [ 819.99987211 1048.3035788 ]
 [ 665.99982918  

71 car:a207df29ec9583f0
train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00057: early stopping
[[192.00003043 157.37616346]
 [196.99998379 194.33436158]
 [360.99991187 405.4437341 ]
 [479.00013488 419.92752047]
 [ 74.00000482  86.78561549]
 [625.99995481 533.44682533]
 [328.99991685 277.28591495]
 [248.99994531 285.09755147]
 [124.99997469  87.28859891]
 [267.00006889 225.15294602]
 [274.99997401 267.77029326]
 [ 83.00000704  76.11931476]
 [455.99991107 463.01976869]
 [356.99994765 303.16183744]
 [969.99974781 865.47573454]
 [365.9999813  437.15002301]
 [245.99993147 278.55677595]
 [163.00003119 104.90847328]
 [225.99994133 219.58559968]
 [275.99992493 239.8650174 ]
 [138.00003108 123.30239298]
 [104.99998589 115.29454269]
 [103.99999232  91.11643822]
 [249.99996866 252.30160973]
 [227.00001875 188.37633798]
 [260.99994013 227.32282615]
 [405.00009986 326.57020675]
 [108.00001109 114.45362748]
 [750.99978762 700.11082628]
 [439.99992146 532.2

train shape: (242, 1, 18)
label shape: (242, 1)
test shape: (22, 1, 18)
batch_size: 9
Epoch 00048: early stopping
[[ 379.99991384  369.66800626]
 [ 172.99996907  269.464104  ]
 [ 301.00004527  244.99114046]
 [ 202.00003439  239.00669157]
 [ 287.99993575  283.65604291]
 [ 376.99991967  368.66079068]
 [ 409.99990442  334.48229181]
 [ 436.99989339  293.44680772]
 [ 295.99997994  230.50594032]
 [ 334.00002345  317.95644821]
 [ 210.99997023  168.73044474]
 [ 188.99996277  177.13419191]
 [ 432.9998972   359.43033217]
 [ 119.99999463   80.16472549]
 [ 284.99996835  322.29572444]
 [ 140.0000052   126.77432906]
 [ 285.99997371  205.18194177]
 [ 126.00002325   96.1875072 ]
 [1580.99966236 1418.19594079]
 [ 263.99994088  241.97645521]
 [ 444.00005553  304.26786025]
 [ 404.00009996  457.68009342]
 [ 295.99997994  285.37771537]
 [ 265.00007515  275.72960099]
 [ 255.00000687  225.45266509]]
validate rmse: 0.8019515200582616
[[ 391.99584961  371.86749268  365.63665771  373.89779663]
 [ 117.60322571  

train shape: (286, 1, 18)
label shape: (286, 1)
test shape: (22, 1, 18)
batch_size: 11
Epoch 00145: early stopping
[[ 160.00002029  256.4711339 ]
 [  44.99999972   65.38515214]
 [ 509.00005687  487.3979173 ]
 [  99.99999236  207.2701643 ]
 [ 326.00008753  312.14265589]
 [ 436.0000121   390.37699987]
 [1428.00001092 1459.19383839]
 [ 262.99995561  277.64753677]
 [ 537.00007324  565.43080627]
 [  86.00000737  105.13550224]
 [ 912.99993957  780.60204689]
 [ 504.99991625  489.5254692 ]
 [ 715.00010464  725.00531326]
 [1465.00033662 1164.99368837]
 [ 668.99998704  659.5509294 ]
 [ 510.00005308  459.77140156]
 [ 152.00001663  264.15981759]
 [ 497.00005302  453.75970205]
 [  61.99999162   60.89631645]
 [ 227.99993794  357.64297383]
 [ 256.00001096  240.08487215]
 [ 215.9999768    65.67920499]
 [ 780.00011482  668.43343025]
 [ 134.99999684   85.49909604]
 [ 429.9999255   660.07772944]
 [2222.00004288 1787.9730449 ]
 [ 637.99982851  560.40618962]
 [ 730.00012491  700.6241436 ]
 [ 513.99994146  

76 car:63065128401bb3ff
train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00038: early stopping
[[2533.00006227 2259.57974589]
 [1810.00017269 1484.95368116]
 [2119.00036708 1648.67599554]
 [1800.99948853 1985.10564363]
 [ 826.99994548  679.30002947]
 [ 882.99989861 1469.95326331]
 [4988.99985057 3143.76291486]
 [7066.00146145 4452.83098846]
 [ 275.99992493  254.73430186]
 [2108.00051678 1262.48486294]
 [2723.0001902  1707.34263958]
 [ 466.00004098  343.49225294]
 [1398.99979179 1546.45116712]
 [1235.00021645  591.42018014]
 [1358.99977231 1352.82679735]
 [2053.00029252 1938.76536867]
 [2760.99926852 2364.04561853]
 [ 365.9999813   272.10775549]
 [1576.99994121 1225.20307943]
 [ 976.99998808  917.68819721]
 [ 407.00005056  229.11385949]
 [ 749.00003914  515.08046597]
 [ 413.00004393  346.06873572]
 [1307.0000319  1267.46929282]
 [1756.0002076  1034.56033034]
 [ 586.99985925  371.29146277]
 [2455.00049599 1714.367978  ]
 [2357.00053167 2118.150

Epoch 00032: early stopping
[[ 203.99997262  137.51601008]
 [ 274.00002607  150.97838484]
 [1114.00009728  541.0578626 ]
 [ 432.9998972   250.70343933]
 [ 136.00003364  218.5987245 ]
 [ 249.99996866  382.45043385]
 [ 635.00007591  573.8784492 ]
 [ 781.99997747  712.77966679]
 [ 234.00000576   92.2576614 ]
 [ 509.00005687  754.7369477 ]
 [ 283.00003144  449.94344174]
 [ 400.99991886  314.42709449]
 [ 900.99998566  160.83806447]
 [ 201.00004069  150.11779994]
 [1908.99992917  527.54580511]
 [ 312.99995326  165.81877157]
 [  46.99999495   58.2652172 ]
 [  52.00000708  107.82499871]
 [ 177.00004151  307.86190655]
 [ 196.99998379   89.56483034]
 [ 851.99984214  672.21749879]
 [  34.00000316   63.92908314]
 [ 298.99995814  138.50834842]
 [  65.99999399  107.41855101]
 [ 176.00002774  140.97228677]]
validate rmse: 0.159341986770123
[[ 493.87817383  490.21444702  154.66792297  146.91902161]
 [ 453.44876099  396.04653931  123.62921143   36.69394684]
 [ 622.93261719  723.24499512  156.62173462  

Epoch 00032: early stopping
[[106.0000048  215.16339149]
 [ 54.00000138  39.18552955]
 [ 38.99999862  21.76131993]
 [ 99.00001008 111.23250903]
 [ 18.99999768  40.02888982]
 [142.00000596 157.35338537]
 [298.99995814 148.69042156]
 [ 88.00000708  53.32111933]
 [134.00000129 146.62835897]
 [ 13.99999905  19.60782684]
 [122.99999157 172.14344025]
 [ 56.99999206  38.94068025]
 [134.99999684 163.2319206 ]
 [290.00005731 151.50587381]
 [588.99997224 299.20612143]
 [111.99998612  54.65053594]
 [185.000003   181.78303732]
 [ 33.00000393  23.82117452]
 [ 80.00000397  91.35970918]
 [ 34.9999959   26.1125498 ]
 [ 43.00000037  55.12862656]
 [120.99999821  83.60788081]
 [109.99999498  76.61260858]
 [ 32.00000315  19.10833783]
 [210.0000483  176.82840817]
 [223.99998952 148.40185625]
 [483.99992854 328.1212233 ]
 [ 63.99999286  34.22898122]
 [358.99992633 186.20072003]]
validate rmse: 0.4203678173049673
79 car:32d3069d17aa47c2
train shape: (264, 1, 18)
label shape: (264, 1)
test shape: (22, 1, 18)


train shape: (308, 1, 18)
label shape: (308, 1)
test shape: (22, 1, 18)
batch_size: 12
Epoch 00055: early stopping
[[190.99994644 184.29756183]
 [126.99997512 134.32034242]
 [301.00004527 323.7600432 ]
 [287.99993575 301.23682802]
 [ 86.00000737  97.26439087]
 [287.00002598 255.13904504]
 [214.99994616 167.7949819 ]
 [263.99994088 201.38382622]
 [ 78.00000326  54.46409455]
 [190.0000514  158.25663165]
 [193.9999998  155.96628579]
 [ 52.99999831  62.96504196]
 [351.00007632 337.26713593]
 [283.00003144 215.40761705]
 [737.99999366 565.18207981]
 [298.00002557 284.604902  ]
 [232.00000846 174.96023377]
 [102.99999683 106.19425568]
 [138.00003108 132.11829227]
 [129.00003593 117.15675129]
 [103.99999232  91.66444819]
 [102.99999683  83.88485961]
 [110.99999676  76.66730526]
 [168.99999388 137.64316094]
 [190.0000514  119.5648212 ]
 [124.99997469 116.08347889]
 [332.00007938 229.13623282]
 [138.00003108 133.31757028]
 [289.0000092  258.15277623]
 [270.99999632 345.12681106]
 [717.99990806 

Epoch 00056: early stopping
[[ 543.99990604  568.95684465]
 [ 475.99987513  415.38889646]
 [ 668.99998704  478.99683328]
 [ 302.99993598  296.02225345]
 [ 381.00002823  349.12025707]
 [ 616.00013695  585.28752154]
 [ 792.00003647  676.4657997 ]
 [ 848.99983586  605.66654767]
 [ 341.99997286  384.38119875]
 [ 656.99983187  668.91506897]
 [ 245.99993147  255.34517775]
 [ 219.00001062  181.98038418]
 [ 819.99987211  673.52268185]
 [ 315.99992899  282.68387946]
 [ 891.99987953  509.40221914]
 [ 234.00000576  183.29800674]
 [ 586.99985925  539.75384997]
 [ 230.00006226  196.73198783]
 [1547.00021605 1213.75902164]
 [ 338.00001384  412.3372968 ]
 [1094.00017903  756.35308828]
 [ 555.00015884  791.30613358]
 [ 425.00003076  409.93255662]
 [ 250.9999714   258.87651139]
 [ 397.0000238   456.47476306]]
validate rmse: 0.7228413970232987
[[ 634.88287354  538.02502441  441.21307373  373.74804688]
 [ 389.39849854  361.04327393  283.27883911  230.66421509]
 [ 688.0668335   591.35510254  568.17529297 

```
all validation rmse: 0.611178786215723
```

In [8]:
submit.sort_values(by=['id'], ascending=True)['forecastVolum'].mean()

471.3008293454306

In [9]:
submit = submit.sort_values(by=['id'], ascending=True)
submit['forecastVolum'] = submit['forecastVolum'].map(lambda index: int(np.round(index)))
print('res store over')

res store over


In [10]:
sub = submit.sort_values(by=['id'], ascending=True)
print(len(sub))
sub.describe()
sub.groupby(['regMonth'])['forecastVolum'].mean()

7216


id         adcode  regYear     regMonth  forecastVolum
count  7216.000000    7216.000000   7216.0  7216.000000    7216.000000
mean   3658.939024  347727.272727   2018.0     2.500000     471.302522
std    2114.152561  136288.963363      0.0     1.118111     618.115307
min       1.000000  110000.000000   2018.0     1.000000       1.000000
25%    1826.750000  230000.000000   2018.0     1.750000     119.000000
50%    3652.500000  355000.000000   2018.0     2.500000     275.000000
75%    5500.250000  440000.000000   2018.0     3.250000     565.250000
max    7304.000000  610000.000000   2018.0     4.000000    8105.000000

regMonth
1    590.483925
2    462.738914
3    430.183481
4    401.803769
Name: forecastVolum, dtype: float64

In [11]:
sub = submit.copy()
sub['forecastVolum'] = sub['forecastVolum'] / thresh
sub['forecastVolum'] = sub['forecastVolum'].map(lambda index: int(np.round(index)))
sub.describe()
sub.groupby(['regMonth'])['forecastVolum'].mean()
sub[['id', 'forecastVolum']].to_csv('./submit/fusai_lstm_2.csv', encoding='utf-8', index=None)

id         adcode  regYear     regMonth  forecastVolum
count  7216.000000    7216.000000   7216.0  7216.000000    7216.000000
mean   3658.939024  347727.272727   2018.0     2.500000     381.067489
std    2114.152561  136288.963363      0.0     1.118111     499.773405
min       1.000000  110000.000000   2018.0     1.000000       1.000000
25%    1826.750000  230000.000000   2018.0     1.750000      96.000000
50%    3652.500000  355000.000000   2018.0     2.500000     222.000000
75%    5500.250000  440000.000000   2018.0     3.250000     457.250000
max    7304.000000  610000.000000   2018.0     4.000000    6553.000000

regMonth
1    477.431264
2    374.138027
3    347.820399
4    324.880266
Name: forecastVolum, dtype: float64