## 分车型预测-LSTM

In [1]:
import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from keras import backend as K
from keras.utils import plot_model
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.preprocessing import MinMaxScaler
from keras.layers import LSTM, RNN, GRU, SimpleRNN
from sklearn.model_selection import train_test_split
from keras.initializers import glorot_uniform

seed = 2019
random.seed(seed)
tf.set_random_seed(seed)
np.random.seed(seed)
warnings.filterwarnings('ignore')

C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: P

In [2]:
data_path = './data/'
train_user_reply_data = pd.read_csv(data_path + 'train_user_reply_data.csv', encoding='utf-8')
train_search_data = pd.read_csv(data_path + 'train_search_data.csv', encoding='utf-8')
train_sales_data = pd.read_csv(data_path + 'train_sales_data.csv', encoding='utf-8')
evaluation_public = pd.read_csv(data_path + 'evaluation_public.csv', encoding='utf-8')

train_sales_data = train_sales_data.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True)
evaluation_public = evaluation_public.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True)

In [3]:
# train_sales_data.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True).to_csv('temp.csv', encoding='utf-8', index=None, sep='\t')
# evaluation_public.sort_values(['regYear', 'regMonth', 'model', 'province'], ascending=True).to_csv('temp_sub.csv', encoding='utf-8', index=None, sep='\t')

In [4]:
cars = ['a50a6db3d691e9ce', 'b135f55ced5c4c67', '9011c3cf495e3c7b', '28e29f2c03dcd84c', '54fc07138d70374c', 'd0f245b8781e3631', 'ffeb3a4cec627e8c', 'a7128d308ae14d73', '7aab7fca2470987e', '42d4439853da7221', '2509a94e62fd3e4b', '9e967965ad4a6c07', '346393c2c6305fb1', '7a7885e2d7c00bcf', '17bc272c93f19d56', 'f8a6975573af1b33', 'feabbf46658382b9', 'fde95ea242abd896', 'd4efbebb087fd03f', '04e66e578f653ab9', '7245e0ee27b195cd', 'f270f6a489c6a9d7', '02aab221aabc03b9', 'b4be3a4917289c82', 'f5d69960089c3614', 'c06a2a387c0ee510', '6858d6dfe680bdf7', '12f8b7e14947c34d', '07a30393ec51530e', 'cc21c7e91a3b5a0c', '3c974920a76ac9c1', '37aa9169b575ef79', 'ea489c253676aafc', '97f15de12cfabbd5', 'fc32b1a017b34efe', 'b25c4e2e3856af22', '854982e5264fb53e', '8527c11fccaa94e2', '283d331fdf05a655', '9a390098bf87b814', 'a28bb927b6fcb33c', 'a9a43d1a7ecbe75d', 'ef76a85c4b39f693', '4a103c30d593fbbe', '0797526c057dcf5b', 'c6cd4e0e073f5ac2', '1181894ae2811540', 'af6f4f548684e14d', '6155b214590c66e6', '5b1c11c3efed5312', '936168bd4850913d', 'c6833cb891626c17', '8cbac8dd8f0e89e2', 'a432c483b5beb856', 'cd5841d44fd7625e', '2a2ab41f8f6ff1cb', '7023efdab9cedc03', 'bb9fbec9a2833839', '79de4e4b24c35b04', '4f79773e600518a6', '28956642949e0e57', '3d7554f1f56dd664', 'b9aa8592ab2492da', '17363f08d683d52b', 'bc5bbd459c18fefd', '0aa15031db420212', '3e21824be728cbec', '7cf283430b3b5e38', '212083a9246d2fd3', 'da457d15788fe8ee', 'a207df29ec9583f0', '2d0d2c3403909fdb', '8c915fe4632fb9fa', '06880909932890ca', 'dff803b4024d261d', '63065128401bb3ff', '9c1c7ee8ebdda299', 'e8a33f68c15dcf7c', '32d3069d17aa47c2', '5f727f32393ade77', '5d7fb682edd0f937', '61e73e32ad101892']
provinces = ['浙江', '福建', '四川', '陕西', '安徽', '湖南', '广东', '云南', '上海', '山东', '湖北', '黑龙江', '江苏', '广西', '内蒙古', '辽宁', '北京', '重庆', '河北', '山西', '江西', '河南']

# Normalization
train_sales_data['salesVolume'] = train_sales_data['salesVolume'].map(lambda index: np.log2(index) + 1)
scaler = MinMaxScaler(feature_range=(0, 1))
train_sales_data[['salesVolume']] = scaler.fit_transform(train_sales_data[['salesVolume']])
train_sales_data.head(3)

province  adcode             model bodyType  regYear  regMonth  \
506       上海  310000  02aab221aabc03b9    Sedan     2016         1   
507       云南  530000  02aab221aabc03b9    Sedan     2016         1   
508      内蒙古  150000  02aab221aabc03b9    Sedan     2016         1   

     salesVolume  
506     0.666707  
507     0.567856  
508     0.469225

In [5]:
def generate_batch(data_set, look_back, gap_days):
    data_x, data_y = [], []
    for i in range(len(data_set) - look_back - gap_days + 1):
        a = data_set[i:(i + look_back), 0]
        data_x.append(a)
        data_y.append([data_set[i + look_back + gap_days - 1, 0]])
    return np.array(data_x), np.array(data_y), data_set[-look_back:, 0].reshape(1, look_back)

In [6]:
def metrics(data):
    data = scaler.inverse_transform(data)
    data = 2 ** (data - 1)
    print(data)
    
    a = data[:, 0]
    b = data[:, 1]
    res = np.sqrt(np.sum((a - b) ** 2) / len(a)) / np.mean(a)
    print('validate rmse:', 1 - res)
    return (1 - res)

In [7]:
from keras.layers.advanced_activations import PReLU

def construct_lstm_model(x_train, x_test, y_train, y_test, test, car_name, batch_size):
    print('batch_size:', batch_size)
#     y_train = scaler.inverse_transform(y_train)
#     y_test = scaler.inverse_transform(y_test)
    model = Sequential()
    model.add(LSTM(32, input_shape=(1, look_back), return_sequences=True, kernel_initializer=glorot_uniform(seed=seed)))
    model.add(LSTM(32, return_sequences=False, kernel_initializer=glorot_uniform(seed=seed)))
    model.add(Dense(units=1, kernel_initializer=glorot_uniform(seed=seed)))
    model.add(PReLU())
    model.compile(loss='mean_squared_error', optimizer='adam')   # loss='mse'  'mean_squared_error'
#     model.summary()
    early_stopping = EarlyStopping('val_loss', patience=20, verbose=1)
    best_model_path = './model/' + car_name + '.h5'
    checkpoint = ModelCheckpoint(best_model_path, monitor='val_loss', mode='min', save_best_only=True, verbose=0, save_weights_only=False)
    callbacks = [checkpoint, early_stopping]
    model.fit(x_train, y_train, epochs=500, batch_size=batch_size, verbose=0, shuffle=False, callbacks=callbacks, validation_data=(x_test, y_test))
    model.load_weights(best_model_path)     # load best model parameters   shuffle=False
    predict = model.predict(test)
    predict = scaler.inverse_transform(predict)
    predict = 2 ** (predict - 1)
#     print(np.hstack((y_test, model.predict(x_test))))
    rmse = metrics(np.hstack((y_test, model.predict(x_test))))
    return predict, rmse

In [8]:
file_name = os.listdir('./model/')
for file in file_name:
    os.remove('./model/' + file)
print(os.listdir('./model/'))

look_back = 10
label_length = 4
batch_size = 16
submit = pd.DataFrame()
flag = 0
all_mse = []
thresh = 1.32

for car in cars:
    labels = np.zeros([len(provinces), label_length])
    rmse_total = 0
    for k in range(1, 5, 1):
        print('{} car:{}'.format(flag+1, car))
        train = np.array([[0 for _ in range(look_back)]])
        label = np.array([[0]])
        test = np.array([[0 for _ in range(look_back)]])

        for province in provinces: 
            temp = train_sales_data[(train_sales_data['model'] == car) & (train_sales_data['province'] == province)]
    #         print(temp[['province', 'model', 'regYear', 'regMonth', 'salesVolume']])
            data = temp['salesVolume'].values.reshape(-1, 1).astype('float32')
            train_data, train_label, test_data = generate_batch(data, look_back, k)
            train = np.vstack((train, train_data))
            label = np.vstack((label, train_label))
            test = np.vstack((test, test_data))

        train = train[1:]
        label = label[1:]
        test = test[1:]
        train = np.reshape(train, (-1, 1, look_back))
        test = np.reshape(test, (-1, 1, look_back))
        x_train,x_test,y_train,y_test = train_test_split(train, label, test_size=0.1, random_state=seed)

        print('train shape:', train.shape)
        print('label shape:', label.shape)
        print('test shape:', test.shape)
        res, rmse = construct_lstm_model(x_train, x_test, y_train, y_test, test, car, int((train.shape[0] * 0.9) / 22))
        K.clear_session()    #  清除tf session
        labels[:, k-1] = res.reshape(1, -1)
        rmse_total += rmse
    print(labels)
    print('average rmse:', rmse_total / 4)
    flag += 1
    all_mse.append(rmse_total / 4)

    index = 0
    submit_partial = pd.DataFrame()
    for province_2 in provinces: 
        temp = evaluation_public[(evaluation_public['model'] == car) & (evaluation_public['province'] == province_2)]
        temp['forecastVolum'] = labels[index]
        submit_partial = pd.concat([submit_partial, temp], axis=0, ignore_index=True)
        index += 1
    submit = pd.concat([submit, submit_partial], axis=0)

print(pd.DataFrame({'car': cars, 'rmse': all_mse}))
print('all validation rmse:', np.mean(all_mse))

[]
1 car:a50a6db3d691e9ce
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00041: early stopping
[[505.99990097 342.79727852]
 [205.00005415 179.20088912]
 [277.00001148 235.07666391]
 [186.99997475 243.64785287]
 [ 69.9999972   68.95579381]
 [108.00001109 128.24203909]
 [438.99998416 309.71591034]
 [456.99998136 320.39880458]
 [129.00003593 145.28597355]
 [215.9999768  152.13418054]
 [291.00005581 275.43185435]
 [146.99999695 147.28786678]
 [155.99997376 253.46859018]
 [326.00008753 315.80994703]
 [469.00003486 527.90894647]
 [279.0000113  244.06876477]
 [250.9999714  183.44335782]
 [179.99997496 203.35032982]
 [174.00002648  96.54247529]
 [245.00000606 310.50464845]
 [208.99994294 202.88342089]
 [ 76.00000245  70.91371466]
 [ 45.99999794  66.20616636]
 [145.99997893 159.69730308]
 [146.99999695 245.18527193]
 [285.99997371 317.27668898]
 [551.00014181 364.20589327]
 [246.99996538 172.06237936]
 [ 96.00000781 104.78751344]
 [263.99994088 235

Epoch 00469: early stopping
[[ 146.99999695  156.21355972]
 [ 233.00000251  176.46952318]
 [1020.00018486 1005.26667509]
 [ 371.00004081  317.29710069]
 [  76.00000245  118.77146172]
 [ 179.99997496   92.84935361]
 [ 384.00009048  368.65592032]
 [ 407.99997673  498.63822427]
 [ 233.00000251  168.10580675]
 [ 308.00004471  269.22600538]
 [ 121.99999587  106.35849568]
 [  93.00000537   81.06236305]
 [ 464.00005273  307.41907987]
 [ 145.00001747  137.69701221]
 [1803.00025245 1763.32704259]
 [ 182.99997653  193.62428016]
 [ 120.99999821  127.13332093]
 [  69.9999972    84.22944674]
 [ 336.00004907  196.27272158]
 [  67.99999205  126.79246211]
 [ 479.00013488  512.38134311]
 [  73.0000048   117.5403483 ]
 [ 195.99997326  245.49896613]
 [  92.00000298  108.79394764]
 [  78.00000326   79.90994389]]
validate rmse: 0.8095170671323608
[[ 524.70202637  360.34442139  465.32901001  430.33694458]
 [ 244.64686584  214.09472656  244.51881409  216.52122498]
 [ 611.76428223  392.9095459   519.2980957  

Epoch 00096: early stopping
[[1001.99976533 1277.45470867]
 [ 556.0001412   428.41250051]
 [ 461.00000027  476.32561914]
 [ 164.99997691  266.84337788]
 [ 311.99997159  344.95716063]
 [1631.00024893 1332.97407889]
 [1131.00006436 1153.06972587]
 [ 182.00003656  253.56309611]
 [1283.99969223 1253.76386034]
 [ 140.99998243  138.93855014]
 [ 650.99994295  656.59616337]
 [ 860.99981585  796.70371331]
 [ 680.99984896  658.90948391]
 [1262.99983346 1777.21587785]
 [ 388.999972    444.87183981]
 [ 272.99995068  341.1559207 ]
 [ 705.00013454 1227.64399554]
 [ 425.00003076  450.82016302]
 [ 140.99998243  137.89559766]
 [ 451.99991752  431.00956516]
 [ 260.99994013  339.90643703]
 [  74.00000482  129.51492166]
 [ 856.00012144  761.74979902]
 [ 150.9999799   135.54607106]
 [1244.00006883 1268.58366178]
 [1111.99972946  666.8817981 ]
 [ 426.99989052  395.7114465 ]
 [ 737.99999366  797.07081005]
 [1590.00008955 1564.30554476]]
validate rmse: 0.722800178026604
4 car:28e29f2c03dcd84c
train shape: (26

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00139: early stopping
[[ 755.99996772  351.81129114]
 [ 104.99998589   88.72521414]
 [ 909.99994715  712.38837274]
 [ 453.000062    431.49755205]
 [ 243.99994048  111.79004256]
 [  68.9999904    63.56315048]
 [ 414.99992771  481.39371187]
 [ 777.0000875   327.97048146]
 [  21.00000262   18.75125796]
 [ 201.00004069  130.78946973]
 [ 362.9999884   295.92263078]
 [  44.99999972   20.50943136]
 [ 515.99992695  406.81330474]
 [  66.99999548   58.91355911]
 [ 169.9999718   133.22731691]
 [ 532.99996301  528.91115314]
 [ 229.00005252  108.27116238]
 [ 136.00003364  103.1883055 ]
 [ 325.00001247  338.13380615]
 [  21.00000262   29.67747236]
 [ 134.99999684   92.39546438]
 [  82.00000212   85.38464796]
 [  65.00000066   82.1140168 ]
 [ 112.9999944   123.09180063]
 [2477.99970042  387.50825647]
 [  26.99999861   39.53957059]
 [  76.00000245   51.50179893]
 [ 314.99995226  164.98907816]
 [ 133.00000263  

Epoch 00304: early stopping
[[ 644.00011222  696.29291217]
 [ 239.99993885  319.44912251]
 [ 879.99991082  759.30174516]
 [ 252.00006595  232.66098118]
 [ 157.00002479  141.85342989]
 [ 355.00009949  292.15835364]
 [ 507.00011852  541.33110716]
 [ 317.9999176   169.52120133]
 [ 207.99994095  190.50109364]
 [ 501.00013178  543.07515725]
 [ 199.00001997  127.07717748]
 [ 118.00000492  100.43090885]
 [1856.99967752 1890.70831557]
 [ 472.0000925   391.7690285 ]
 [1397.00031787 1192.69886122]
 [ 909.99994715 1027.19073807]
 [ 459.00011542  363.36296797]
 [ 220.99999952  190.25592622]
 [ 488.99994471  608.48263988]
 [ 308.99998517  385.43579175]
 [ 315.99992899  219.32920417]
 [ 121.99999587  230.9757802 ]
 [ 888.00017958  800.05365926]
 [ 109.99999498  124.29289387]
 [ 104.99998589   99.73887012]]
validate rmse: 0.82304165523959
[[1043.40075684 1061.8170166   832.50543213  976.26403809]
 [ 246.96504211  280.07254028  185.00601196  176.04666138]
 [ 674.27172852  729.81494141  592.73114014  6

Epoch 00213: early stopping
[[243.99994048 341.95891886]
 [ 29.00000267  19.85254031]
 [ 39.9999989   25.57694483]
 [102.99999683 147.98595254]
 [ 25.00000141  28.95221868]
 [217.99998923 217.16052234]
 [142.00000596 129.93039917]
 [ 56.99999206  49.51906886]
 [302.99993598 282.9135663 ]
 [ 12.00000164  20.51076849]
 [310.99996922 256.93751564]
 [ 36.99999956  37.47155537]
 [371.00004081 279.74073318]
 [301.00004527 283.96855194]
 [756.99981739 655.82309574]
 [ 63.00000677  46.81719377]
 [181.00005018 245.15936007]
 [ 29.00000267  26.65449409]
 [ 36.99999956  54.96757401]
 [ 26.99999861  35.87672592]
 [ 50.99999993  46.26895211]
 [ 38.99999862  48.67220963]
 [ 36.99999956  51.07647074]
 [ 21.99999838  18.01874493]
 [295.00008259 300.29754015]
 [375.0000253  277.20724617]
 [848.00023469 850.86767362]
 [ 31.00000232  28.02875534]
 [230.00006226 218.81932194]]
validate rmse: 0.7708766691749075
9 car:7aab7fca2470987e
train shape: (264, 1, 10)
label shape: (264, 1)
test shape: (22, 1, 10)
b

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
[[162.00000134 115.93375106]
 [ 17.00000027  21.97213327]
 [317.9999176  252.13558568]
 [ 83.00000704  80.56197904]
 [371.00004081 190.99994644]
 [  5.00000014   9.86900319]
 [179.99997496  97.81150287]
 [229.00005252 137.55574691]
 [ 45.99999794  34.80463205]
 [ 23.99999825  35.83702724]
 [160.00002029 134.77832828]
 [118.9999846   68.97540243]
 [ 99.99999236  97.80636232]
 [ 31.00000232  24.62873376]
 [ 41.99999641  27.70359428]
 [ 96.99999242  86.22813214]
 [ 50.99999993  55.67710791]
 [ 29.00000267  30.35615324]
 [ 48.99999983  37.4639261 ]
 [ 26.00000154  50.29770715]
 [ 21.99999838  21.7767561 ]
 [110.99999676  78.59470705]
 [ 99.00001008 108.75464821]
 [ 33.00000393  54.65984413]
 [ 25.00000141  21.46357383]
 [ 63.00000677  48.09591848]
 [ 26.99999861  17.75529908]
 [ 80.00000397  59.05848574]
 [ 34.9999959   31.95288249]
 [110.99999676  85.60646897]
 [ 16.00000034  20.94862606]]
validate rmse

[[ 86.00000737  85.27953708]
 [ 44.99999972  44.1954671 ]
 [ 56.99999206  56.41076836]
 [ 65.99999399  75.53429496]
 [ 41.99999641  63.27212021]
 [ 85.00000375 110.66148273]
 [ 74.00000482  66.67869291]
 [ 91.00001126  56.19962828]
 [ 68.9999904   69.10563402]
 [ 76.00000245  82.25488003]
 [ 28.00000025  23.49322727]
 [ 43.00000037  38.84443005]
 [136.00003364 111.87640818]
 [ 76.9999993   58.5763187 ]
 [ 76.00000245 106.01455748]
 [ 78.99999275  77.37045909]
 [106.99999041  75.30370193]
 [ 52.99999831  62.72329888]
 [124.00002842  98.96055368]
 [ 99.99999236  93.81328621]
 [ 60.99999323  62.79981459]
 [  1.           2.30988883]
 [ 90.00000639  86.27717965]
 [ 60.99999323  73.01598215]
 [ 54.00000138  41.8596218 ]]
validate rmse: 0.7746230847332061
[[112.28729248  85.74356842  70.84251404  58.05463028]
 [ 59.47902298  59.86550903  44.21831894  33.44527817]
 [107.25426483  66.3164444   54.38563919  39.637146  ]
 [ 37.51929474  30.92029953  24.13778114  30.7195034 ]
 [105.5426712   86.8

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00122: early stopping
[[ 713.99995038  762.92989298]
 [ 287.00002598  298.9669852 ]
 [ 527.00004788  459.40604684]
 [ 217.00004704  504.05257197]
 [ 351.00007632  307.46464074]
 [1812.99997186 1242.71026936]
 [1447.99990484 1229.42932284]
 [ 356.00005067  348.09883892]
 [1860.00044686 1709.48481984]
 [ 157.00002479  217.57166513]
 [1729.0000029  1530.69939528]
 [ 819.99987211  747.86382898]
 [1675.99991064 1690.65402636]
 [2048.00056167 2030.11846039]
 [ 679.99999212  737.57748419]
 [ 432.9998972   461.85926631]
 [ 481.99992506  683.41956097]
 [ 413.00004393  383.64227699]
 [ 398.00007065  359.08695628]
 [ 497.00005302  474.43280728]
 [ 356.00005067  456.17543341]
 [ 335.00008305  396.12169732]
 [ 819.00007314  658.59277805]
 [ 214.99994616  203.03334007]
 [1738.9997924  1995.91012502]
 [2662.00052873 1796.30390043]
 [ 896.00009632  933.51209298]
 [ 801.9998996   782.67582925]
 [1915.99973462 1

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00179: early stopping
[[ 425.00003076  325.74346578]
 [ 304.00005671  249.84450009]
 [ 483.99992854  404.27146324]
 [ 475.99987513  479.73806294]
 [  48.0000002    46.30895384]
 [ 225.00000496  242.20951399]
 [ 705.99984761  608.27541676]
 [ 839.99984033  766.36933701]
 [  76.00000245   76.53976969]
 [ 281.99998662  266.43873767]
 [ 513.00005822  412.36335044]
 [  65.00000066   78.52968108]
 [ 455.99991107  386.48706222]
 [ 425.99988821  325.48667212]
 [ 780.00011482  784.06621449]
 [ 569.99998068  525.75377284]
 [ 661.00007268  551.80398106]
 [ 160.00002029  178.12908778]
 [ 227.00001875  188.36854759]
 [ 109.99999498  109.64525722]
 [ 178.0000116   136.20657674]
 [  50.00000668   60.12292945]
 [  36.99999956   49.94179711]
 [ 169.9999718   201.10709417]
 [ 521.99992053  365.42776828]
 [ 115.99999528   81.88315909]
 [ 614.00002669  482.41622151]
 [ 436.0000121   220.58161803]
 [ 106.0000048   

Epoch 00421: early stopping
[[ 932.00015386  755.04046975]
 [ 967.00018177  875.70184953]
 [2048.00056167 1628.46059372]
 [ 501.99998152  652.68705359]
 [ 425.99988821  524.9568235 ]
 [1084.00015253 1105.84927221]
 [1188.99970719 1231.22361133]
 [ 809.99979695  617.5905126 ]
 [ 995.99993493  884.17990108]
 [ 611.00009881  724.26027211]
 [ 551.99989244  446.80426431]
 [ 368.00006871  324.09495432]
 [2438.99988288 1160.29494859]
 [ 473.99998489  492.09288555]
 [3059.99962308 2263.53657078]
 [ 764.99978773  901.42549433]
 [1043.00015698 1429.9222904 ]
 [ 353.99990699  310.75765426]
 [ 784.99992067  890.64469666]
 [ 291.99998039  401.81219875]
 [1422.99962042 1018.15047959]
 [ 287.00002598  570.44935616]
 [ 650.00007508  758.91324585]
 [ 542.00003445  460.37735788]
 [ 461.00000027  303.66881696]]
validate rmse: 0.6196905489439976
[[1747.81591797  700.73468018  597.4465332   711.07214355]
 [ 499.61599731  283.20321655  229.18022156  250.96794128]
 [2081.51123047 1301.6583252  1136.37683105 

Epoch 00044: early stopping
[[1105.99982303  529.24392202]
 [ 210.99997023  258.60290507]
 [1000.99997273  843.74408198]
 [ 149.00000129  313.24185757]
 [ 555.00015884  686.72062269]
 [1001.99976533  877.87749553]
 [2155.00023016 1572.3680627 ]
 [ 602.00013698  663.17499825]
 [1575.0002581  1577.65679604]
 [ 403.0000229   498.56118475]
 [2339.99963214 1588.48110897]
 [ 905.00001653  938.19789551]
 [1096.9998011  1650.84033614]
 [ 820.99994843 1067.36815839]
 [1038.00017476 1166.1921087 ]
 [ 753.00011748  680.45322443]
 [ 268.00002326  641.58286412]
 [ 980.00017544  835.8193678 ]
 [ 103.99999232  171.881909  ]
 [ 684.99983495 1026.29431218]
 [ 455.99991107  633.28374606]
 [ 126.00002325  174.35148574]
 [ 691.99998307  706.68591761]
 [ 469.99999906  507.64032705]
 [1343.00028379 1619.43406344]
 [4324.00091771 1548.91808473]
 [1078.00022623 1256.24940985]
 [1162.99994798 1013.16602949]
 [1049.99996959  941.8673798 ]]
validate rmse: 0.404861268583245
19 car:d4efbebb087fd03f
train shape: (2

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
[[1215.999716    810.93224575]
 [ 348.0000798   365.20240604]
 [ 830.99978147  823.33852097]
 [ 654.00014427  648.60634151]
 [ 676.00007983  431.90942611]
 [  44.99999972   44.07569553]
 [1232.99997975 1207.32725523]
 [2366.99951902 1163.24313241]
 [ 205.00005415  181.33158656]
 [ 642.99991522  409.61315855]
 [ 822.99997984  694.18958032]
 [ 328.00005909  185.94474508]
 [ 535.00012083  437.48435957]
 [ 252.00006595  161.07215167]
 [ 510.99995931  421.40386303]
 [ 880.99978462  858.94888076]
 [ 617.00015321  548.77402422]
 [ 370.00003455  268.59981775]
 [ 856.99979978  720.25150122]
 [ 250.9999714   304.92675415]
 [ 291.99998039  213.76817269]
 [ 291.99998039  233.38174069]
 [ 212.00002596  225.39763496]
 [ 340.99997407  407.85587545]
 [ 657.99988447  331.55224002]
 [ 326.00008753  277.265529  ]
 [ 861.99988667  522.56661282]
 [ 816.00001641  587.20455635]
 [  80.00000397   80.92984058]
 [ 720.0000109

Epoch 00083: early stopping
[[ 319.00007288  313.18572631]
 [ 145.00001747  124.68810994]
 [ 529.99988676  513.79774317]
 [ 778.00000401  742.62094537]
 [ 197.99997857  168.6957518 ]
 [ 678.00000702  586.64560187]
 [ 430.99991008  413.75106677]
 [ 541.00006062  434.50123365]
 [1016.00003614  916.80254647]
 [ 450.99990877  485.83992658]
 [  93.00000537   89.6300869 ]
 [ 126.99997512  102.66058002]
 [ 379.99991384  282.70921058]
 [  54.99999325   65.31298907]
 [ 596.00009713  550.98653288]
 [ 114.99998923  126.18202933]
 [ 256.9999509   254.86938885]
 [  61.99999162   79.49508121]
 [ 503.00009315  476.2347932 ]
 [ 497.99992904  380.51122611]
 [ 609.00013207  433.11307603]
 [  58.99999791  111.16461342]
 [ 843.00000192  572.5275621 ]
 [ 786.00019964 1073.02350665]
 [  69.9999972    56.87782138]]
validate rmse: 0.7532628013511227
[[289.40109253 279.22296143 243.59954834 235.7835083 ]
 [104.29439545  89.91081238  81.37693787  76.76023102]
 [402.12408447 394.4045105  348.52880859 334.2521972

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00049: early stopping
[[139.00001385 167.47289933]
 [ 26.00000154  33.75264996]
 [ 61.99999162  66.24719266]
 [ 37.99999829  80.83590136]
 [ 38.99999862  38.62571026]
 [102.00000774 121.28692762]
 [102.00000774  91.09333451]
 [ 61.99999162  60.19482081]
 [152.00001663 190.2386605 ]
 [ 25.00000141  29.75891293]
 [299.9999719  343.43859163]
 [184.00002016 131.13218556]
 [386.00008907 348.48274607]
 [339.99996983 397.75005149]
 [202.00003439 225.20002572]
 [ 88.99999894  77.6382567 ]
 [168.99999388 127.97360381]
 [ 68.9999904   68.34253773]
 [ 45.99999794  40.28171524]
 [ 60.99999323  68.05797992]
 [ 88.00000708  82.46478074]
 [ 16.00000034  30.71609967]
 [ 94.99999109  83.06145855]
 [ 31.00000232  28.91813072]
 [217.99998923 202.99707419]
 [567.00004138 353.71596174]
 [231.00006026 227.63092514]
 [154.00001047 128.03742394]
 [118.00000492 113.11740617]]
validate rmse: 0.6702189865418724
24 car:b4

26 car:c06a2a387c0ee510
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00038: early stopping
[[ 118.9999846   118.83745025]
 [ 154.00001047  167.65991112]
 [ 145.00001747  235.10272545]
 [ 275.99992493  309.8755266 ]
 [  75.00000294   85.04483547]
 [1184.00010247 1301.95511552]
 [ 909.00005335  797.78534813]
 [ 950.00001097  915.83094858]
 [ 322.99996572  150.34094772]
 [ 353.00009933  233.39058834]
 [ 684.99983495  596.54877564]
 [  94.99999109  139.83830358]
 [ 308.00004471  304.34704109]
 [ 186.99997475  202.48014548]
 [ 753.99989752  643.24224448]
 [ 253.99996984  408.10826191]
 [ 356.99994765  420.68002524]
 [ 102.99999683   84.94138704]
 [ 433.99987828  398.46716315]
 [ 413.00004393  323.35972108]
 [ 118.9999846   112.92641448]
 [ 186.99997475  171.23803059]
 [ 130.9999878   109.99601451]
 [ 186.99997475  169.95711025]
 [ 207.99994095  200.48347593]
 [ 324.00002768  282.42274409]
 [ 368.00006871  323.61056141]
 [  96.99999242  106.182

Epoch 00220: early stopping
[[1650.00041682 1648.43547807]
 [ 185.99997167  216.06959068]
 [ 274.99997401  311.23246186]
 [ 223.99998952  212.49951075]
 [ 234.9999814   216.90745679]
 [ 640.00017989  563.06423203]
 [ 585.99999502  534.84557104]
 [ 483.99992854  413.31021265]
 [ 166.00002688  206.06326398]
 [ 538.00007009  588.37103758]
 [  76.00000245   79.0149459 ]
 [  78.00000326   83.68708553]
 [2058.99952617 2226.45624565]
 [ 138.00003108  169.25344575]
 [ 390.00002732  476.04034169]
 [ 325.00001247  393.38694653]
 [ 409.00001026  362.90909172]
 [ 201.00004069  184.32868708]
 [1394.00005822 1519.69696218]
 [1004.0000405  1184.80219023]
 [ 436.99989339  420.08795144]
 [ 410.99988229  492.95290679]
 [ 919.00006615  819.61891973]
 [ 248.99994531  252.35436624]
 [  63.99999286  102.3050332 ]]
validate rmse: 0.8623900973173094
[[1819.27062988 1891.05847168 1800.60168457 2122.58862305]
 [ 411.47717285  394.55212402  401.8843689   388.64450073]
 [ 637.04284668  609.84362793  623.41784668 

validate rmse: 0.6109125143256566
29 car:07a30393ec51530e
train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00045: early stopping
[[ 38.99999862  53.62844292]
 [118.9999846  101.80389704]
 [166.00002688 188.98834717]
 [ 87.00000653 109.49634895]
 [ 63.00000677  83.74178221]
 [360.99991187 319.10783118]
 [196.99998379 248.85882076]
 [ 44.99999972  59.61532504]
 [234.00000576 299.63281491]
 [ 58.99999791  99.84342061]
 [ 99.99999236  91.26281046]
 [371.99997203 277.58550643]
 [ 80.00000397 106.14013441]
 [132.00003608 162.0439277 ]
 [203.99997262 207.5093638 ]
 [ 45.99999794  68.63887029]
 [ 37.99999829  46.43811484]
 [178.99997609 183.81410264]
 [ 61.99999162  53.27636103]
 [199.9999427  258.61270888]
 [ 60.99999323  76.76797423]
 [ 50.99999993  61.14327387]
 [ 91.00001126  66.9966859 ]
 [ 88.99999894  83.04206672]
 [219.00001062 372.06215644]
 [294.00001659 159.56178509]
 [274.00002607 277.34437362]
 [287.99993575 318.98028449]
 [348.99995842 

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00036: early stopping
[[473.99998489 298.12158048]
 [168.00001157 199.41079563]
 [453.000062   397.52302217]
 [304.00005671 412.67090767]
 [219.00001062 201.82989383]
 [240.99994394 285.4942856 ]
 [344.00008256 382.79438281]
 [368.99996836 335.40672442]
 [400.99991886 335.08533674]
 [331.00003959 307.3756444 ]
 [306.99998966 375.16656451]
 [457.99987729 312.98593034]
 [331.00003959 410.7586839 ]
 [324.00002768 300.00496917]
 [621.00007058 537.84280008]
 [302.99993598 389.12757655]
 [158.00004306 173.76451704]
 [383.00002067 346.64806607]
 [292.9999749  336.81006369]
 [804.9998076  691.46835904]
 [376.99991967 348.67616019]
 [176.00002774 210.71462335]
 [176.00002774 204.06642235]
 [322.99996572 336.91435553]
 [130.9999878  137.67771506]
 [691.99998307 675.12117519]
 [501.99998152 376.04896746]
 [261.99999581 166.62430539]
 [292.9999749  416.66902668]
 [329.99997927 387.38185046]
 [648.99987899 

Epoch 00095: early stopping
[[ 538.00007009  589.8860151 ]
 [ 962.99988057  541.34354477]
 [2086.00047489 1642.66036382]
 [1049.99996959 1753.15010453]
 [ 605.00000815  599.90522271]
 [3174.99955735 2179.19699835]
 [3096.00063644 2782.71429568]
 [3148.0002658  3038.55454152]
 [1333.00011128  867.65737131]
 [2375.99938611 3475.54949044]
 [1027.99996223  794.51015692]
 [ 672.00014998  953.5913115 ]
 [ 978.99984048  551.80017764]
 [ 425.00003076  348.58244306]
 [2931.99926888 1846.85062453]
 [ 479.00013488  342.92686348]
 [1283.99969223 1206.60555776]
 [ 295.99997994  293.46197796]
 [2005.00022674 1642.67168626]
 [ 421.99997302  567.66025508]
 [3648.00013288 2886.99321848]
 [ 277.00001148  369.53362277]
 [ 625.99995481  670.83970224]
 [ 764.99978773  930.35117795]
 [ 742.99982408  718.6670917 ]]
validate rmse: 0.658660868527343
[[ 832.83789062  761.42211914  690.36126709  601.23486328]
 [ 627.64093018  558.175354    564.12780762  458.24105835]
 [3313.45898438 2967.70385742 2240.42944336 2

Epoch 00090: early stopping
[[ 375.0000253   561.17926676]
 [ 172.00002801  172.64022673]
 [ 451.99991752  506.86588506]
 [ 505.99990097  959.39959775]
 [ 201.00004069  173.55933084]
 [ 790.00001073  658.1510821 ]
 [ 591.00011094  552.05221064]
 [ 327.00004691  457.32506906]
 [ 726.99987536  793.71967642]
 [ 101.00000941  140.62307634]
 [1108.00021688  917.24342094]
 [ 353.00009933  329.72960262]
 [1009.99991042  961.57659642]
 [ 803.00016217  996.4147906 ]
 [2147.9993906  2407.71324368]
 [ 481.99992506  559.75505575]
 [ 438.00005504  499.80357202]
 [ 386.99998998  513.73104994]
 [ 448.0000136   409.48330512]
 [ 436.99989339  568.89508187]
 [ 433.99987828  483.19604674]
 [ 571.00009438  496.32992808]
 [ 315.99992899  304.88226985]
 [ 103.99999232  118.78275292]
 [ 846.00018827  834.53419856]
 [1515.00015777 1211.32066479]
 [2376.99996425 2585.87261857]
 [ 331.00003959  368.61653628]
 [ 799.99989425  759.75153635]]
validate rmse: 0.7781828841816893
34 car:97f15de12cfabbd5
train shape: (

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00255: early stopping
[[1560.99976974  779.88722025]
 [ 461.00000027  439.21033482]
 [1320.00012077  973.98269108]
 [ 616.00013695  775.86730301]
 [ 429.9999255   232.91530123]
 [ 612.0000831   534.30822076]
 [ 571.00009438  567.19222571]
 [ 283.00003144  396.04821207]
 [ 280.99992477  221.4918072 ]
 [ 207.99994095  274.7801842 ]
 [ 644.00011222  612.70671185]
 [ 352.00008264  288.21076459]
 [ 679.99999212  678.6966809 ]
 [ 533.99987225  382.27517184]
 [1368.99996712 1186.82103569]
 [ 542.00003445  653.17197804]
 [ 574.00009625  537.09755203]
 [ 236.99997416  131.89703701]
 [ 205.00005415  223.20266539]
 [ 265.00007515  203.6709731 ]
 [ 196.99998379  135.0552188 ]
 [ 140.99998243  151.06669259]
 [ 177.00004151  196.8885572 ]
 [ 438.99998416  410.01356372]
 [ 166.99999884  165.88917269]
 [ 212.00002596  236.6946926 ]
 [ 234.00000576  355.38222777]
 [1144.00007135  613.97075516]
 [ 271.99993203  

Epoch 00040: early stopping
[[ 561.99989291  492.72077945]
 [ 182.00003656  173.88143287]
 [ 726.0000328   675.36086886]
 [ 356.00005067  378.54532044]
 [ 139.00001385  117.98028305]
 [ 291.99998039  264.39267643]
 [ 809.99979695  893.38380801]
 [ 381.99992236  328.87786145]
 [ 102.99999683  112.44611427]
 [ 809.99979695  764.50341478]
 [ 197.99997857  219.08518845]
 [ 217.00004704  201.11668211]
 [1009.00024915  702.39830186]
 [ 373.00002731  322.50850266]
 [ 917.00004467  753.2665958 ]
 [ 674.99980939  575.9618694 ]
 [ 386.99998998  344.30213461]
 [ 291.00005581  223.04771803]
 [ 482.99986261  532.75234394]
 [ 236.00002804  421.83130058]
 [ 466.00004098  406.3644373 ]
 [ 213.99999734  423.84035068]
 [ 578.000063    805.29440163]
 [  83.99999931   99.03604057]
 [ 164.00001689  130.44255458]]
validate rmse: 0.7433795328931156
[[ 824.6953125   783.5425415   869.22454834  823.3482666 ]
 [ 248.23054504  218.36695862  235.8500824   244.33026123]
 [ 390.53530884  354.97412109  384.0904541  

Epoch 00091: early stopping
[[  75.00000294   83.2696389 ]
 [ 138.00003108  179.44046843]
 [ 870.99992542  855.2064254 ]
 [  69.9999972   213.27660851]
 [ 647.00001368  450.27954499]
 [ 784.99992067  537.48887908]
 [1542.0002407  1514.16846942]
 [ 403.0000229   298.812473  ]
 [1389.9998858  1332.43593473]
 [ 154.00001047  221.57413602]
 [1259.00019799 1097.18506885]
 [ 707.00016612  634.68027973]
 [ 905.00001653 1193.79549002]
 [2086.00047489 1989.99640881]
 [ 673.99985762  529.87721634]
 [ 856.99979978  745.72421089]
 [  36.00000432   59.31572113]
 [ 736.0001942   595.54461885]
 [  90.00000639   82.56594805]
 [ 499.00009691  641.08260797]
 [ 433.99987828  511.80423537]
 [  74.00000482  109.03142038]
 [1419.99980144 1216.27214667]
 [ 322.99996572  209.9733924 ]
 [1268.9997982  1618.0087069 ]
 [2027.00041062 1558.85024137]
 [ 541.00006062  748.80345417]
 [ 761.00021783  831.88663875]
 [ 816.99990726  632.31653637]]
validate rmse: 0.7735024870083833
39 car:283d331fdf05a655
train shape: (

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00024: early stopping
[[ 673.99985762  519.98325022]
 [ 450.99990877  326.15067309]
 [ 438.00005504  493.68113656]
 [ 426.99989052  445.25888254]
 [ 176.00002774  175.71961659]
 [ 161.00000321  238.47339068]
 [ 853.99984693  562.81137418]
 [ 750.00010847  610.06376902]
 [ 233.00000251  287.38702679]
 [ 450.00004463  294.07247143]
 [ 438.99998416  574.47671304]
 [ 287.99993575  308.65585122]
 [ 290.00005731  475.39793143]
 [ 676.00007983  520.45118543]
 [1437.99987795  981.46876918]
 [ 370.00003455  447.02785483]
 [ 328.99991685  302.31064823]
 [ 442.99993346  399.77206202]
 [ 344.00008256  290.86519827]
 [ 596.00009713  561.12253821]
 [ 433.99987828  420.19292817]
 [ 203.99997262  193.17559751]
 [ 147.99997855  185.59272771]
 [ 332.00007938  266.2918592 ]
 [ 213.99999734  210.98263978]
 [ 645.99998127  643.68169907]
 [ 830.99978147  560.80934523]
 [ 351.00007632  288.65294652]
 [ 164.00001689  

Epoch 00048: early stopping
[[277.00001148 283.30986494]
 [277.00001148 212.28004133]
 [124.99997469 119.84129145]
 [ 78.00000326 112.77628895]
 [227.99993794 192.63720064]
 [223.00006356 226.26725409]
 [158.00004306 142.33162332]
 [137.00000247  89.30215009]
 [ 78.00000326 102.49778193]
 [163.00003119 151.72175983]
 [ 28.00000025  34.53006736]
 [ 45.99999794  29.67237588]
 [353.99990699 300.17768432]
 [ 85.00000375  82.41399506]
 [152.99999717 118.77272383]
 [168.99999388 152.1520081 ]
 [373.00002731 310.1527816 ]
 [ 82.00000212  76.07796459]
 [409.99990442 459.02199861]
 [185.000003   254.1253253 ]
 [130.9999878   88.74297658]
 [ 66.99999548  81.0497691 ]
 [213.00005002 300.43124878]
 [ 87.00000653 107.14024193]
 [ 86.00000737  81.61307095]]
validate rmse: 0.7752576915372791
[[300.91665649 293.73007202 296.8223877  290.94213867]
 [104.30670166  94.22267914  97.14674377  94.12525177]
 [217.52056885 203.58023071 209.8263092  205.15515137]
 [234.80285645 235.26460266 228.36842346 221.97

Epoch 00095: early stopping
[[ 497.00005302  702.7017639 ]
 [ 439.99992146  555.61416574]
 [1178.00003536  822.97539848]
 [ 423.0000615  1053.78164653]
 [ 589.9998718   468.58185807]
 [3260.00028255 1894.96700567]
 [3302.99923193 2396.79322537]
 [ 541.00006062  564.11503349]
 [2082.99998463 1731.05699599]
 [ 223.99998952  310.26093729]
 [1452.99967625 1251.47083082]
 [2474.99968086 1883.55097315]
 [1416.99979504 1379.18861205]
 [2484.99962157 2294.22762862]
 [ 994.00018273 1037.39935871]
 [ 938.00014208  935.5508149 ]
 [ 492.99991173  692.3689429 ]
 [ 998.00027081  742.63672813]
 [ 771.99979427  712.16130792]
 [ 564.99998794  705.63051416]
 [ 667.00017178  748.42118612]
 [1078.00022623  857.08988715]
 [1638.00027265 1274.99970416]
 [ 274.00002607  289.29563966]
 [1856.00049729 2120.7781359 ]
 [2896.99993475 1753.09472054]
 [1081.00006263 1133.54040192]
 [2533.00006227 2289.99353201]
 [4173.00067725 2609.49225794]]
validate rmse: 0.6304724034100035
44 car:4a103c30d593fbbe
train shape: (

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00065: early stopping
[[ 890.99980412  474.25788749]
 [ 376.99991967  283.37040743]
 [ 630.99986246  828.87889315]
 [ 833.99989357  240.91081232]
 [ 339.99996983  212.91687113]
 [ 233.00000251  175.92715462]
 [1188.99970719  694.08631492]
 [1763.99969863  764.29749263]
 [  33.00000393   49.49907717]
 [ 124.00002842   71.10533369]
 [ 557.00000567  486.98403518]
 [  60.99999323   94.72058143]
 [ 230.00006226  266.34065671]
 [ 120.99999821   95.77639314]
 [ 341.99997286  290.41529028]
 [ 297.00002512  348.76309134]
 [ 551.00014181  378.53705804]
 [ 136.00003364  133.76184116]
 [ 270.99999632  209.98183508]
 [  52.00000708   70.03522785]
 [ 136.00003364  104.31357503]
 [ 110.99999676   93.81422922]
 [  63.99999286   97.2439174 ]
 [  61.99999162   92.65979199]
 [ 122.99999157   58.90704536]
 [ 101.00000941   84.67937628]
 [ 542.00003445  276.94242076]
 [1240.99974492  454.03866881]
 [  50.99999993  

Epoch 00068: early stopping
[[ 490.00004992  492.69332772]
 [ 394.99997489  276.51897211]
 [1250.00023759 1088.49433566]
 [1344.99972315 1070.91831691]
 [ 327.00004691  267.86320785]
 [ 421.99997302  435.72912515]
 [1243.00010771  994.1680553 ]
 [ 922.00007167  656.85719914]
 [ 637.99982851  323.30716217]
 [1228.00014812 1158.62798399]
 [ 391.99997677  266.29828344]
 [ 416.99991462  270.88996665]
 [ 694.99988928  391.91329894]
 [ 292.9999749   227.41280854]
 [1739.99994841 1102.97875913]
 [ 393.0000695   355.31303473]
 [ 436.99989339  385.75982393]
 [ 256.00001096  239.52398685]
 [1273.99970486 1314.33416303]
 [ 350.00009641  503.91738222]
 [ 578.99991269  545.31449011]
 [  33.00000393  106.8046031 ]
 [1066.9997555   840.46605518]
 [ 410.99988229  341.01015936]
 [ 155.99997376   78.45123426]]
validate rmse: 0.7026594746040133
[[ 521.04418945  449.78573608  346.17050171  278.5854187 ]
 [ 259.23571777  245.28373718  196.72312927  149.1877594 ]
 [ 375.74768066  291.65518188  269.30697632 

Epoch 00355: early stopping
[[ 375.99993867  442.21004327]
 [ 566.00010654  478.61180258]
 [2245.99939361 2033.48307204]
 [ 414.99992771  791.19841947]
 [ 959.99990354 1073.23986288]
 [3049.00077407 1981.68334262]
 [4187.99887239 3944.9110054 ]
 [ 740.00012619  611.78357974]
 [3248.99909498 2888.15755821]
 [ 538.00007009  693.4248241 ]
 [2275.00040995 2148.09686272]
 [1860.00044686 2246.08196068]
 [1890.00036963 2276.52589228]
 [2563.99943877 2760.19374926]
 [2038.00013833 1783.00517354]
 [1849.00003162 1720.05035389]
 [ 234.9999814   247.71775933]
 [1639.99987074 1283.48942934]
 [ 778.00000401  626.02584439]
 [1156.99996521 1575.35673818]
 [1027.99996223 1259.11446263]
 [1021.99999747 1080.3638079 ]
 [1685.00004555 1624.28668897]
 [ 574.00009625  552.29357271]
 [2002.00009992 2237.83126215]
 [4335.99878861 3655.97129745]
 [1364.00010674 1625.508418  ]
 [2496.00035039 2393.4350513 ]
 [2481.00050625 2229.80298079]]
validate rmse: 0.8100272740131845
49 car:6155b214590c66e6
train shape: (

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00049: early stopping
[[ 952.99993968  642.42032101]
 [ 316.99998477  300.27856698]
 [ 364.0001012   407.15460719]
 [  63.99999286  342.10960532]
 [ 373.99997834  337.24195276]
 [ 175.0000347   282.17335729]
 [1295.0002047   818.76536317]
 [1705.00040815  907.47464575]
 [ 607.00008723  551.62081295]
 [ 555.00015884  343.43227909]
 [ 919.00006615  917.33141051]
 [ 629.99995312  527.49096158]
 [ 295.99997994  412.96968032]
 [ 612.0000831   580.21807918]
 [ 650.00007508  644.99371443]
 [ 528.99987104  337.06901455]
 [ 621.99998643  344.86880104]
 [ 306.00001794  299.56501241]
 [ 433.99987828  359.57198775]
 [ 270.99999632  655.7888169 ]
 [ 297.00002512  316.33408064]
 [ 393.0000695   329.14281321]
 [ 398.99988643  370.72332729]
 [ 388.999972    279.20826114]
 [ 322.00003127  164.21880204]
 [ 730.00012491  697.30350826]
 [2055.00005965  971.07064528]
 [ 413.99996722  351.52142868]
 [ 410.99988229  

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00403: early stopping
[[1178.9998496  1034.19493458]
 [ 379.00003007  290.66661869]
 [1224.99971305 1189.07756642]
 [ 509.00005687  465.00564895]
 [ 154.00001047  161.47678094]
 [ 284.99996835  319.27375479]
 [ 807.99979814  662.67503464]
 [ 843.00000192  560.08792736]
 [ 310.99996922  331.73054105]
 [ 542.99998524  651.24566127]
 [ 185.99997167  157.86705348]
 [ 116.99999385  114.33742287]
 [3318.00036489 2803.30360019]
 [ 630.99986246  369.58244524]
 [2375.00059334 2284.46781924]
 [ 888.99995196  763.0490986 ]
 [ 368.00006871  310.12801979]
 [ 289.0000092   225.71505207]
 [ 459.99989579  550.99412852]
 [ 581.00013167  686.29159772]
 [1013.0001857   623.35982097]
 [ 202.99998922  479.02269643]
 [ 574.00009625  555.73896388]
 [ 234.9999814   225.79428163]
 [ 233.00000251  157.94814022]]
validate rmse: 0.7529691440176914
[[2560.7800293  1123.7019043   711.8895874   610.84417725]
 [ 489.5043335   

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00484: early stopping
[[  32.00000315   60.48430649]
 [  74.00000482   80.99585373]
 [ 358.99992633  401.79812031]
 [  86.00000737  250.34153489]
 [ 122.99999157   93.72107922]
 [ 184.00002016  121.66161367]
 [ 425.00003076  463.07961253]
 [ 138.00003108  166.56708191]
 [ 181.00005018  196.61777647]
 [  65.99999399   85.23935518]
 [ 292.9999749   247.30774219]
 [ 287.00002598  182.54959286]
 [ 292.9999749   277.6430714 ]
 [ 345.99996484  385.87794299]
 [ 491.9999009   622.23297176]
 [ 243.00004887  320.37580104]
 [  48.0000002    55.84211574]
 [ 299.9999719   216.08498073]
 [  60.99999323   74.22462319]
 [ 133.00000263  164.61384276]
 [  99.99999236  107.25159598]
 [ 112.9999944    88.49904809]
 [ 140.99998243  152.76570714]
 [ 102.99999683   65.2528984 ]
 [ 187.99995483  224.97415875]
 [1101.99973566  651.47351041]
 [ 467.00004659  427.0168142 ]
 [ 393.0000695   395.16813268]
 [ 217.00004704  

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00044: early stopping
[[2769.99961116 1562.95564228]
 [1040.99991136  836.64985392]
 [1384.99969873  987.08959542]
 [1020.00018486 1036.49700057]
 [ 831.99989217  600.94538114]
 [ 284.99996835  384.64490758]
 [2676.99964725 2499.85850975]
 [3490.99940424 2351.33879337]
 [ 505.99990097  595.00540803]
 [ 644.00011222  507.94191564]
 [2840.99997059 2456.62409867]
 [ 740.00012619  536.52527152]
 [ 837.99989067 1073.77261795]
 [ 426.99989052  351.0456436 ]
 [ 876.00017766 1033.34996881]
 [ 933.00015955 1021.85383749]
 [ 990.0002051  1086.6415008 ]
 [ 718.9998835   708.33545111]
 [ 552.99986885  564.67068382]
 [ 371.99997203  371.46552966]
 [ 602.99993852  704.38650168]
 [ 640.00017989  607.9303181 ]
 [ 504.99991625  622.95606729]
 [ 638.99995553  510.10610859]
 [ 898.99989209  543.3032323 ]
 [ 292.9999749   364.39861503]
 [1786.99971436 1098.43108191]
 [1291.00007699  814.2821491 ]
 [ 129.99997401  

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
[[ 845.00023594  613.00381663]
 [ 140.0000052   118.52366713]
 [ 271.99993203  217.94527596]
 [  96.99999242  182.2467079 ]
 [  78.00000326  109.18556011]
 [ 192.00003043  169.46366435]
 [ 517.00001492  543.40840996]
 [ 163.00003119  154.58954905]
 [  88.99999894   61.2644534 ]
 [ 399.99991627  633.81432135]
 [  70.9999975    53.29593433]
 [  28.00000025   47.49776831]
 [1173.99980908  964.0353629 ]
 [ 188.99996277  165.03845999]
 [ 640.00017989  409.24652276]
 [ 459.99989579  422.08578919]
 [ 231.00006026  288.84384575]
 [ 169.9999718   159.85019681]
 [ 210.99997023  261.77180038]
 [ 308.99998517  534.37850617]
 [ 289.0000092   181.17313097]
 [  85.00000375   58.40719018]
 [ 627.99983535  751.36567777]
 [  54.99999325   48.31342461]
 [  50.99999993   62.93678403]]
validate rmse: 0.6249603098258754
[[1055.83972168  642.02880859  531.17498779  445.87991333]
 [ 254.13183594  132.88198853  135.9556427   

test shape: (22, 1, 10)
batch_size: 11
Epoch 00075: early stopping
[[ 127.9999956   183.32780486]
 [ 206.99996764  177.36245041]
 [ 851.00013046 1090.28269258]
 [ 312.99995326  527.27073586]
 [ 340.99997407  466.71418852]
 [1168.00010177 1012.08416997]
 [3240.99921699 4609.11748077]
 [ 319.00007288  390.27252272]
 [1693.99985947 2287.00567714]
 [1205.99997009 2297.93492486]
 [ 733.00012515  745.42229309]
 [ 447.00012455  503.66360138]
 [ 679.99999212  886.87111229]
 [1387.00032021 1390.38397236]
 [2551.00019306 2949.6258376 ]
 [ 450.00004463  695.36166151]
 [  83.99999931  192.06488808]
 [ 856.00012144  960.95488175]
 [ 469.00003486  450.01917233]
 [ 807.99979814 1225.18618958]
 [ 406.00000976  659.50698524]
 [ 605.99991871  571.94184064]
 [1031.99993353  952.60753707]
 [1325.99969575 1661.48140176]
 [1729.0000029  2585.22956034]
 [2646.00005818 1319.21486019]
 [3262.99956907 4286.94027422]
 [ 423.0000615   645.91686963]
 [1268.9997982  1201.78661549]]
validate rmse: 0.5086871786046185

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00126: early stopping
[[335.00008305 258.33819428]
 [149.00000129 161.384798  ]
 [299.9999719  379.61726217]
 [234.9999814  279.64257421]
 [342.99994894 196.63132925]
 [ 31.00000232  41.20661565]
 [348.0000798  377.93091665]
 [406.00000976 389.54912528]
 [766.9999589  492.7216285 ]
 [154.99997147 143.86371091]
 [403.0000229  354.39256141]
 [486.00013524 542.66168406]
 [229.00005252 277.47328109]
 [364.0001012  256.07663269]
 [332.00007938 297.17118099]
 [205.99995039 228.79376539]
 [134.99999684 116.10911925]
 [328.99991685 243.14232005]
 [118.00000492 107.39461389]
 [661.00007268 705.30188482]
 [239.99993885 205.62744562]
 [152.00001663 179.15498743]
 [168.00001157 217.89971292]
 [134.00000129 158.19537588]
 [ 73.0000048   90.24781275]
 [736.99983897 748.12462215]
 [322.00003127 186.90730158]
 [232.00000846 124.34330754]
 [ 63.00000677  81.32950752]
 [272.99995068 285.05792477]
 [283.00003144 

Epoch 00042: early stopping
[[1847.00020598 1775.9760134 ]
 [ 571.99999155  497.21963059]
 [ 860.99981585  944.83402921]
 [ 486.00013524  729.97538621]
 [ 368.99996836  428.93179184]
 [ 806.00010798  836.34955409]
 [1501.99969111 1176.06982498]
 [ 992.99981647  724.76423568]
 [ 429.9999255   441.20812439]
 [1229.0000429  1184.740943  ]
 [ 451.99991752  412.66758918]
 [ 407.00005056  369.54466033]
 [2119.00036708 2085.36553377]
 [ 469.99999906  556.27677809]
 [1027.99996223 1070.69689366]
 [ 556.0001412   419.38275421]
 [1006.00026391  838.8547074 ]
 [ 513.00005822  496.95609205]
 [8990.00245018 8710.49798129]
 [1205.00009977 1613.97839646]
 [1183.00012496  793.73244192]
 [ 260.99994013  479.93815997]
 [1634.99981112 1938.69521228]
 [ 353.99990699  390.34852371]
 [ 257.99994357  274.70932683]]
validate rmse: 0.8429123683071644
[[ 1987.64489746  2126.23413086  2310.33642578  2192.88549805]
 [ 1596.05969238  1659.01000977  1737.74023438  1659.49597168]
 [  974.77697754   847.76574707   92

Epoch 00136: early stopping
[[ 29.00000267  61.76512884]
 [ 65.99999399  66.49566095]
 [281.99998662 185.82889733]
 [ 58.99999791 125.78150008]
 [ 90.00000639  71.44778209]
 [149.00000129  95.38933354]
 [257.99994357 117.16415387]
 [ 15.00000017  27.38394342]
 [208.99994294 188.56849462]
 [ 19.99999791  23.54836231]
 [108.00001109 112.60226788]
 [ 44.00000015  59.46440365]
 [150.9999799  142.80831166]
 [129.00003593 133.94713423]
 [ 26.00000154  28.83139708]
 [178.0000116  130.60066782]
 [ 10.99999992  30.01680835]
 [155.99997376  99.26712317]
 [ 34.00000316  38.49732096]
 [147.99997855 195.10789088]
 [118.9999846  109.3995665 ]
 [ 50.99999993  40.53901316]
 [ 88.00000708 102.04463234]
 [  2.00000001  24.67940226]
 [152.99999717 308.89368845]
 [453.000062   810.84374973]
 [ 63.00000677  59.87808115]
 [ 88.00000708  78.91661106]
 [ 91.00001126  93.96973898]]
validate rmse: 0.2631164849145945
64 car:17363f08d683d52b
train shape: (264, 1, 10)
label shape: (264, 1)
test shape: (22, 1, 10)


66 car:0aa15031db420212
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00130: early stopping
[[1261.99982229  597.82274934]
 [ 366.9999273   334.63179795]
 [1333.99968024  826.12304298]
 [ 558.99999466  484.00687874]
 [ 432.9998972   230.35637569]
 [  90.00000639  225.85848963]
 [ 569.99998068  629.47654813]
 [1069.99970961  458.56688509]
 [ 136.00003364  136.78322068]
 [  98.00000722   69.31730721]
 [ 803.00016217  615.4187211 ]
 [ 438.00005504  286.89915499]
 [ 574.99996238  431.79631379]
 [ 315.99992899  251.04120817]
 [ 712.99996652  582.62194643]
 [ 513.00005822  491.86229327]
 [ 205.99995039  171.64699878]
 [ 243.00004887  189.8138497 ]
 [ 134.99999684  165.04642313]
 [ 268.00002326  264.02936063]
 [ 238.00005591  165.24334851]
 [  71.99999351   83.52798339]
 [  92.00000298  116.08551258]
 [ 139.00001385  107.16735401]
 [ 186.99997475   93.05814294]
 [ 368.99996836  253.74856989]
 [ 356.00005067  211.12617398]
 [1372.99964098  675.208

[[457.99987729 297.93978011]
 [174.00002648 172.53811866]
 [591.00011094 548.35495227]
 [334.00002345 379.35830765]
 [187.99995483 194.37834654]
 [321.00005791 403.16695488]
 [431.99998693 480.07601637]
 [454.99993847 412.66024121]
 [225.99994133 200.26295774]
 [464.00005273 466.49468473]
 [ 87.00000653  71.39283134]
 [ 87.00000653  82.84528037]
 [829.99991946 697.90375498]
 [223.99998952 212.32333168]
 [766.9999589  589.83282174]
 [309.99996687 327.10130112]
 [194.99999862 154.28537002]
 [194.99999862 129.44962152]
 [393.99999799 315.1139612 ]
 [386.00008907 420.11063385]
 [454.99993847 480.30218659]
 [ 58.99999791  69.12828305]
 [709.99984595 790.8499262 ]
 [199.00001997 156.20449745]
 [ 39.9999989   43.56514994]]
validate rmse: 0.8040816616765232
[[459.75115967 471.54052734 381.98712158 279.71380615]
 [224.54498291 230.59103394 175.31944275 133.45135498]
 [294.52020264 295.06466675 260.21640015 195.36320496]
 [155.39637756 155.28063965 125.20887756  84.51493835]
 [261.47393799 268.7

[[  50.00000668  126.82370949]
 [ 118.9999846   151.93777893]
 [ 903.99990479 1191.21522051]
 [  92.00000298  281.51285145]
 [ 283.00003144  296.61745701]
 [ 696.99997534  521.10508662]
 [1872.00047934 2475.37075227]
 [ 233.00000251  256.47776317]
 [ 551.00014181  933.6112958 ]
 [ 187.99995483  171.46548676]
 [ 425.99988821  544.62301502]
 [ 607.00008723  581.13597261]
 [ 360.99991187  537.52037046]
 [ 888.99995196 1059.61451907]
 [ 794.00010886  913.05343207]
 [ 406.00000976  703.22707902]
 [  85.00000375  104.15527469]
 [ 665.99982918  608.84169078]
 [  93.00000537   73.40455794]
 [ 403.0000229   497.28018139]
 [ 243.00004887  287.84513938]
 [ 145.00001747  184.8831509 ]
 [1035.99999683  668.16242101]
 [ 223.99998952  160.22561705]
 [ 503.00009315  897.87798387]
 [1849.99969365 1362.28694595]
 [ 855.00013589  538.89388989]
 [ 819.99987211 1268.93711394]
 [ 665.99982918  575.7376113 ]]
validate rmse: 0.562237782486338
69 car:212083a9246d2fd3
train shape: (264, 1, 10)
label shape: (264

average rmse: 0.7460822692838364
71 car:a207df29ec9583f0
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00038: early stopping
[[192.00003043 184.79014694]
 [196.99998379 186.85030303]
 [360.99991187 410.84339401]
 [479.00013488 471.20991617]
 [ 74.00000482 108.28916795]
 [625.99995481 543.13006124]
 [328.99991685 316.2356145 ]
 [248.99994531 314.91962788]
 [124.99997469 112.81756004]
 [267.00006889 260.74610494]
 [274.99997401 304.47730603]
 [ 83.00000704  97.46088131]
 [455.99991107 460.43051291]
 [356.99994765 313.85924463]
 [969.99974781 811.31475277]
 [365.9999813  515.40453316]
 [245.99993147 275.94048165]
 [163.00003119 136.78149221]
 [225.99994133 260.03641013]
 [275.99992493 268.87596994]
 [138.00003108 146.29723432]
 [104.99998589 136.64995685]
 [103.99999232 120.01150602]
 [249.99996866 262.95071291]
 [227.00001875 228.24601655]
 [260.99994013 268.7237347 ]
 [405.00009986 365.36711244]
 [108.00001109 145.00917933]
 [750.99978762 7

Epoch 00039: early stopping
[[ 379.99991384  346.88070725]
 [ 172.99996907  269.59879482]
 [ 301.00004527  315.68897702]
 [ 202.00003439  278.24830473]
 [ 287.99993575  238.27239248]
 [ 376.99991967  330.88408416]
 [ 409.99990442  346.76994421]
 [ 436.99989339  313.27046679]
 [ 295.99997994  271.84889483]
 [ 334.00002345  348.49235418]
 [ 210.99997023  165.7931526 ]
 [ 188.99996277  151.64334695]
 [ 432.9998972   371.17610309]
 [ 119.99999463  118.19380678]
 [ 284.99996835  326.18383373]
 [ 140.0000052   144.29977075]
 [ 285.99997371  243.12653906]
 [ 126.00002325  110.51014697]
 [1580.99966236 1346.27040948]
 [ 263.99994088  313.42255335]
 [ 444.00005553  320.53299411]
 [ 404.00009996  491.82302423]
 [ 295.99997994  351.15595704]
 [ 265.00007515  284.31324845]
 [ 255.00000687  238.90690707]]
validate rmse: 0.7826848502174708
[[ 410.22244263  409.44949341  391.80725098  384.30761719]
 [ 128.16120911  118.97589874  118.99536133  126.07525635]
 [ 402.31018066  372.47540283  409.88632202 

validate rmse: 0.5016237512943982
74 car:06880909932890ca
train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00413: early stopping
[[ 160.00002029  258.66515072]
 [  44.99999972   72.12000603]
 [ 509.00005687  556.43720106]
 [  99.99999236  204.50433555]
 [ 326.00008753  316.74953805]
 [ 436.0000121   394.87475406]
 [1428.00001092 1868.37605072]
 [ 262.99995561  272.22203247]
 [ 537.00007324  612.72993997]
 [  86.00000737  114.6184611 ]
 [ 912.99993957  819.79077373]
 [ 504.99991625  473.73079388]
 [ 715.00010464  802.84704581]
 [1465.00033662 1268.68713655]
 [ 668.99998704  675.44427739]
 [ 510.00005308  528.60531201]
 [ 152.00001663  282.86173239]
 [ 497.00005302  481.53309272]
 [  61.99999162   63.24921005]
 [ 227.99993794  370.44788407]
 [ 256.00001096  259.17794668]
 [ 215.9999768    72.07474245]
 [ 780.00011482  699.82174812]
 [ 134.99999684   91.84229276]
 [ 429.9999255   715.42488546]
 [2222.00004288 2072.41912612]
 [ 637.99982851  616.

76 car:63065128401bb3ff
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00024: early stopping
[[2533.00006227 1760.76843346]
 [1810.00017269 1344.95646056]
 [2119.00036708 1900.39527728]
 [1800.99948853 1795.71175361]
 [ 826.99994548  644.32090343]
 [ 882.99989861 1933.72392423]
 [4988.99985057 2824.44431281]
 [7066.00146145 2881.83067288]
 [ 275.99992493  485.25982185]
 [2108.00051678 1107.57961797]
 [2723.0001902  2880.96673377]
 [ 466.00004098  523.16967922]
 [1398.99979179 1849.5130744 ]
 [1235.00021645 1123.01831658]
 [1358.99977231 1933.89276071]
 [2053.00029252 1803.20842631]
 [2760.99926852 1745.65096708]
 [ 365.9999813   620.61923372]
 [1576.99994121 1271.23658946]
 [ 976.99998808  768.49888357]
 [ 407.00005056  603.73848158]
 [ 749.00003914  676.63678654]
 [ 413.00004393  611.13944355]
 [1307.0000319  1048.16268788]
 [1756.0002076   952.71861932]
 [ 586.99985925  796.20917836]
 [2455.00049599 1230.03961018]
 [2357.00053167 1590.420

validate rmse: -0.002980283591964783
77 car:9c1c7ee8ebdda299
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00024: early stopping
[[ 203.99997262  152.06463811]
 [ 274.00002607  123.56922761]
 [1114.00009728  265.8866808 ]
 [ 432.9998972   393.08947135]
 [ 136.00003364  197.08600071]
 [ 249.99996866  370.54471287]
 [ 635.00007591  554.84142497]
 [ 781.99997747  632.19415039]
 [ 234.00000576   96.21900454]
 [ 509.00005687  634.70579917]
 [ 283.00003144  344.90109127]
 [ 400.99991886  360.99265449]
 [ 900.99998566  176.23846582]
 [ 201.00004069   89.85617562]
 [1908.99992917  260.98000198]
 [ 312.99995326  102.36234348]
 [  46.99999495  106.11130133]
 [  52.00000708  132.58186776]
 [ 177.00004151  364.31887738]
 [ 196.99998379  152.05546718]
 [ 851.99984214  568.5530571 ]
 [  34.00000316   46.34546281]
 [ 298.99995814  199.81633614]
 [  65.99999399  122.70026995]
 [ 176.00002774  205.48163025]]
validate rmse: 0.013677522730861869
[[ 695.966003

Epoch 00033: early stopping
[[106.0000048  283.5576502 ]
 [ 54.00000138  51.23886469]
 [ 38.99999862  38.31636898]
 [ 99.00001008 132.4473717 ]
 [ 18.99999768  53.43227425]
 [142.00000596 213.94272422]
 [298.99995814 237.71164525]
 [ 88.00000708  71.62251426]
 [134.00000129 205.69088101]
 [ 13.99999905  31.82724337]
 [122.99999157 223.38787178]
 [ 56.99999206  57.29212776]
 [134.99999684 217.44573014]
 [290.00005731 206.79674953]
 [588.99997224 384.48012358]
 [111.99998612  87.58737992]
 [185.000003   250.89762967]
 [ 33.00000393  37.79247986]
 [ 80.00000397 124.54402219]
 [ 34.9999959   36.76505789]
 [ 43.00000037  80.42528531]
 [120.99999821 133.68495454]
 [109.99999498  83.17835851]
 [ 32.00000315  30.32508011]
 [210.0000483  206.93434559]
 [223.99998952 173.56690755]
 [483.99992854 410.67918083]
 [ 63.99999286  60.11434832]
 [358.99992633 227.22256845]]
validate rmse: 0.5148688361118774
79 car:32d3069d17aa47c2
train shape: (264, 1, 10)
label shape: (264, 1)
test shape: (22, 1, 10)


train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00055: early stopping
[[190.99994644 182.09812111]
 [126.99997512 134.4514116 ]
 [301.00004527 359.02652804]
 [287.99993575 341.48979982]
 [ 86.00000737 102.35417113]
 [287.00002598 278.8473294 ]
 [214.99994616 185.16180561]
 [263.99994088 189.1014939 ]
 [ 78.00000326  71.90774538]
 [190.0000514  160.6138195 ]
 [193.9999998  184.7735895 ]
 [ 52.99999831  74.62633916]
 [351.00007632 353.0783737 ]
 [283.00003144 228.35892411]
 [737.99999366 615.25542931]
 [298.00002557 338.95052227]
 [232.00000846 189.00734501]
 [102.99999683 112.39871646]
 [138.00003108 142.34519518]
 [129.00003593 138.99737914]
 [103.99999232 105.21742178]
 [102.99999683  97.28439367]
 [110.99999676 105.17192319]
 [168.99999388 157.37959854]
 [190.0000514  122.47353988]
 [124.99997469 144.89810998]
 [332.00007938 241.73709455]
 [138.00003108 136.45324363]
 [289.0000092  300.18665029]
 [270.99999632 329.56846734]
 [717.99990806 

82 car:61e73e32ad101892
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00045: early stopping
[[ 543.99990604  606.57801076]
 [ 475.99987513  470.96963159]
 [ 668.99998704  486.99746194]
 [ 302.99993598  455.21403355]
 [ 381.00002823  428.68425592]
 [ 616.00013695  691.71187   ]
 [ 792.00003647  634.21709811]
 [ 848.99983586  712.20426057]
 [ 341.99997286  346.8564001 ]
 [ 656.99983187  686.49976753]
 [ 245.99993147  262.56192904]
 [ 219.00001062  246.80694883]
 [ 819.99987211  559.67114545]
 [ 315.99992899  268.2803358 ]
 [ 891.99987953  506.55940701]
 [ 234.00000576  205.72455579]
 [ 586.99985925  502.93769034]
 [ 230.00006226  265.35420967]
 [1547.00021605 1478.46502893]
 [ 338.00001384  606.0124498 ]
 [1094.00017903  691.30593366]
 [ 555.00015884  728.08933176]
 [ 425.00003076  597.14734885]
 [ 250.9999714   348.62529349]
 [ 397.0000238   508.22762742]]
validate rmse: 0.7048426252649295
[[ 671.09545898  572.83880615  440.21322632  560.727

```
all validation rmse: 0.6483414301351754
```

In [9]:
submit = submit.sort_values(by=['id'], ascending=True)
submit['forecastVolum'] = submit['forecastVolum'].map(lambda index: int(np.round(index)))
print('res store over')

res store over


In [10]:
sub = submit.sort_values(by=['id'], ascending=True)
print(len(sub))
sub['forecastVolum'].mean()
sub.groupby(['regMonth'])['forecastVolum'].mean()

7216


505.5597283813747

regMonth
1    578.380266
2    506.344235
3    477.557095
4    459.957317
Name: forecastVolum, dtype: float64

In [11]:
sub = submit.copy()
sub['forecastVolum'] = sub['forecastVolum'] / thresh
sub['forecastVolum'] = sub['forecastVolum'].map(lambda index: int(np.round(index)))
sub.groupby(['regMonth'])['forecastVolum'].mean()
sub.describe()
sub[['id', 'forecastVolum']].to_csv('./submit/fusai_lstm_1.csv', encoding='utf-8', index=None)

regMonth
1    438.177938
2    383.589246
3    361.787694
4    348.456208
Name: forecastVolum, dtype: float64

id         adcode  regYear     regMonth  forecastVolum
count  7216.000000    7216.000000   7216.0  7216.000000    7216.000000
mean   3658.939024  347727.272727   2018.0     2.500000     383.002772
std    2114.152561  136288.963363      0.0     1.118111     508.446941
min       1.000000  110000.000000   2018.0     1.000000       1.000000
25%    1826.750000  230000.000000   2018.0     1.750000      98.000000
50%    3652.500000  355000.000000   2018.0     2.500000     227.000000
75%    5500.250000  440000.000000   2018.0     3.250000     461.000000
max    7304.000000  610000.000000   2018.0     4.000000    8486.000000