## 分车型预测-使用LSTM建模预测

In [1]:
import os
import warnings
import numpy as np
import pandas as pd
from keras import backend as K
import matplotlib.pyplot as plt
from keras.utils import plot_model
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.preprocessing import MinMaxScaler
from keras.layers import LSTM, RNN, GRU, SimpleRNN
from sklearn.model_selection import train_test_split

np.random.seed(1904)
warnings.filterwarnings('ignore')

C:\ProgramFiles\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framew

### 导入数据

In [2]:
data_path = './data/'
train_user_reply_data = pd.read_csv(data_path + 'train_user_reply_data.csv', encoding='utf-8')
train_search_data = pd.read_csv(data_path + 'train_search_data.csv', encoding='utf-8')
train_sales_data = pd.read_csv(data_path + 'train_sales_data.csv', encoding='utf-8')
evaluation_public = pd.read_csv(data_path + 'evaluation_public.csv', encoding='utf-8')

### 提取车型和省份数据

In [3]:
cars = list(set(train_sales_data['model']))
provinces = list(set(train_sales_data['province']))
print(len(cars))
print(len(provinces))

# Normalization
train_sales_data['salesVolume'] = train_sales_data['salesVolume'].map(lambda index: np.log2(index) + 1)   # log变换
scaler = MinMaxScaler(feature_range=(0, 1))
train_sales_data[['salesVolume']] = scaler.fit_transform(train_sales_data[['salesVolume']])
print(train_sales_data[:3])

60
22
  province  adcode             model bodyType  regYear  regMonth  salesVolume
0       上海  310000  3c974920a76ac9c1      SUV     2016         1     0.557228
1       云南  530000  3c974920a76ac9c1      SUV     2016         1     0.609492
2      内蒙古  150000  3c974920a76ac9c1      SUV     2016         1     0.542952


### 构造数据

In [4]:
def generate_batch(data_set, look_back, gap_days):
    data_x, data_y = [], []
    for i in range(len(data_set) - look_back - gap_days + 1):
        a = data_set[i:(i + look_back), 0]
        data_x.append(a)
        data_y.append([data_set[i + look_back + gap_days - 1, 0]])
    return np.array(data_x), np.array(data_y), data_set[-look_back:, 0].reshape(1, look_back)

### 自定义评测指标

In [5]:
def metrics(data):
    data = scaler.inverse_transform(data)
    data = 2 ** (data - 1)
    print(data)
    
    a = data[:, 0]
    b = data[:, 1]
    res = np.sqrt(np.sum((a - b) ** 2) / len(a)) / np.mean(a)
    print('validate rmse:', 1 - res)
    return (1 - res)

### 模型构建

In [6]:
from keras.layers.advanced_activations import PReLU

def construct_lstm_model(x_train, x_test, y_train, y_test, test, car_name, batch_size):
    print('batch_size:', batch_size)
    model = Sequential()
    model.add(LSTM(32, input_shape=(1, look_back), return_sequences=True))
    model.add(LSTM(32, return_sequences=False))
    model.add(Dense(1))
    model.add(PReLU())
    model.compile(loss='mean_squared_error', optimizer='adam')   # loss='mse'  'mean_squared_error'
#     model.summary()
    early_stopping = EarlyStopping('val_loss', patience=20, verbose=1)
    best_model_path = './model/' + car_name + '.h5'
    checkpoint = ModelCheckpoint(best_model_path, monitor='val_loss', mode='min', save_best_only=True, verbose=0, save_weights_only=False)
    callbacks = [checkpoint, early_stopping]
    model.fit(x_train, y_train, epochs=500, batch_size=batch_size, verbose=0, shuffle=False, callbacks=callbacks, validation_data=(x_test, y_test))
    model.load_weights(best_model_path)     # load best model parameters   shuffle=False
    predict = model.predict(test)
    predict = scaler.inverse_transform(predict)
    predict = 2 ** (predict - 1)
#     print(np.hstack((y_test, model.predict(x_test))))
    rmse = metrics(np.hstack((y_test, model.predict(x_test))))
    return predict, rmse

### 分车型&分月建模预测

In [7]:
file_name = os.listdir('./model/')
for file in file_name:
    os.remove('./model/' + file)
print(os.listdir('./model/'))

look_back = 10
label_length = 4
batch_size = 16
submit = pd.DataFrame()
flag = 0
total = 0
thresh = 1.42

for car in cars:
    labels = np.zeros([len(provinces), label_length])
    rmse_total = 0
    for k in range(1, 5, 1):
        print('{} car:{}'.format(flag+1, car))
        train = np.array([[0 for _ in range(look_back)]])
        label = np.array([[0]])
        test = np.array([[0 for _ in range(look_back)]])

        for province in provinces: 
            temp = train_sales_data[(train_sales_data['model'] == car) & (train_sales_data['province'] == province)]
    #         print(temp[['province', 'model', 'regYear', 'regMonth', 'salesVolume']])
            data = temp['salesVolume'].values.reshape(-1, 1).astype('float32')
            train_data, train_label, test_data = generate_batch(data, look_back, k)
            train = np.vstack((train, train_data))
            label = np.vstack((label, train_label))
            test = np.vstack((test, test_data))

        train = train[1:]
        label = label[1:]
        test = test[1:]
        train = np.reshape(train, (-1, 1, look_back))
        test = np.reshape(test, (-1, 1, look_back))
        x_train,x_test,y_train,y_test = train_test_split(train, label, test_size=0.1, random_state=1904)

        print('train shape:', train.shape)
        print('label shape:', label.shape)
        print('test shape:', test.shape)
        res, rmse = construct_lstm_model(x_train, x_test, y_train, y_test, test, car, int((train.shape[0] * 0.9) / 22))
        K.clear_session()    #  清除tf session
        labels[:, k-1] = res.reshape(1, -1)
        rmse_total += rmse
    print(labels)
    print('average rmse:', rmse_total / 4)
    flag += 1
    total += rmse_total / 4

    index = 0
    submit_partial = pd.DataFrame()
    for province_2 in provinces: 
        temp = evaluation_public[(evaluation_public['model'] == car) & (evaluation_public['province'] == province_2)]
        temp['forecastVolum'] = labels[index]
        submit_partial = pd.concat([submit_partial, temp], axis=0)
        index += 1
    submit = pd.concat([submit, submit_partial], axis=0)

print('all validation rmse:', total / 60)  

[]
1 car:a28bb927b6fcb33c
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00053: early stopping
[[ 264.00000696  283.85612722]
 [  72.00000749  125.7837234 ]
 [ 246.00004064  260.90778502]
 [ 614.99985624  436.66512963]
 [  85.00001022  179.53512283]
 [ 397.00005391  400.2316373 ]
 [ 553.00010217  352.91053456]
 [ 966.00011997  494.06891349]
 [ 826.99996804  575.8824708 ]
 [ 676.99983797  548.28360617]
 [1051.00012938  882.36676129]
 [ 664.99983093  482.69388822]
 [ 330.99997547  257.53116118]
 [ 175.99997209  196.07322477]
 [3988.00086191 2817.88412695]
 [ 316.99995616  219.88468265]
 [ 220.99999662  213.16041953]
 [ 577.99998394  452.7563407 ]
 [ 316.99995616  212.18893418]
 [ 547.99987753  467.1498425 ]
 [ 466.99995201  368.97101786]
 [ 680.00008208  915.04508824]
 [ 164.99998246  142.72866468]
 [ 466.00000584  292.86609913]
 [5245.00033686 2987.73199729]
 [2391.00023935 3156.43250346]
 [ 344.99997916  428.38630127]
 [ 906.00010767  624.8

Epoch 00067: early stopping
[[1488.99989501 1125.80177224]
 [ 668.99990517  648.35257394]
 [ 352.00003806  319.13362242]
 [ 546.00012889  707.98957003]
 [ 579.00007907  637.19415999]
 [ 228.00000256  264.42550298]
 [ 139.00001451  150.6949012 ]
 [  72.00000749   81.04996911]
 [ 289.99994741  465.25287766]
 [ 181.99996076  209.04015444]
 [1385.00032736 1333.54829474]
 [ 730.00003891  621.34134123]
 [ 168.99999955  106.02433172]
 [ 388.00006849  301.56827308]
 [ 206.00002693  294.04185532]
 [ 242.00005203  328.28468495]
 [1073.99999953 1345.86189002]
 [ 513.99987826  503.13408912]
 [ 502.00003655  409.0200943 ]
 [1730.00011248 1935.85542096]
 [ 301.00004187  225.30674607]
 [ 358.000029    287.18986043]
 [ 303.00000948  267.26932118]
 [  76.99999176   60.49295038]
 [ 135.99999815  123.80952757]]
validate rmse: 0.7582905038830908
[[1539.95922852  881.82843018  654.80059814  582.18554688]
 [ 595.63537598  393.66452026  237.04420471  233.22531128]
 [2335.3894043  1509.53540039 1096.54992676 

Epoch 00088: early stopping
[[1139.99986203 1433.60179487]
 [3929.00100446 3595.1531676 ]
 [2788.99956999 3100.38140324]
 [ 466.99995201  422.6785846 ]
 [1289.99983666 1682.58454432]
 [ 462.99991421  585.49229015]
 [ 910.00016858 1222.95592261]
 [1405.99979289 1559.53320617]
 [1579.00012914 2038.66726526]
 [1034.99985319 1371.24636569]
 [1501.0003378  1645.95674442]
 [1541.00027305 1938.88660215]
 [2583.00035078 3142.70361454]
 [1881.00006956 1651.75794196]
 [6576.00150243 3823.57533764]
 [ 875.00016483 1074.98405008]
 [2280.9996254  2960.13775958]
 [ 112.0000059   170.44424641]
 [2327.99960121 1644.99624552]
 [2071.00024592 1762.44195501]
 [ 197.00001339  225.1529426 ]
 [2165.00052997 1718.74973288]
 [1562.00011824 1550.18946182]
 [3669.00046546 3918.03505321]
 [ 235.00001511  239.910856  ]
 [ 988.00009031 1061.94888644]
 [1719.99992282 1756.50200877]
 [ 667.99995115 1002.5023338 ]
 [ 674.99983638  420.95883901]]
validate rmse: 0.6404584662128263
4 car:17bc272c93f19d56
train shape: (2

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00089: early stopping
[[188.00003701 170.22618538]
 [ 61.99999271  99.04391284]
 [323.99998087 354.93853773]
 [201.00004198 220.60991787]
 [257.00000759 312.14620423]
 [179.99999488 190.48764558]
 [271.0000524  306.51772478]
 [201.00004198 206.16789133]
 [172.99998799 127.30400154]
 [258.00000145 251.1687332 ]
 [792.99992997 659.14500542]
 [241.00001318 225.60083762]
 [103.9999999  128.51116985]
 [125.99998606 147.69766966]
 [409.00003513 478.54590508]
 [139.00001451 151.71676165]
 [155.99998713 137.5358259 ]
 [191.00001793 166.25797837]
 [145.00001233 164.57648172]
 [161.99999041 172.10636183]
 [297.00003849 253.60608211]
 [806.99991589 701.43572922]
 [ 96.99999124  86.51345952]
 [158.00002097 124.8336075 ]
 [588.99998514 460.29632622]
 [580.99988865 501.11557803]
 [175.00000947 187.25698416]
 [366.00003594 216.73951968]
 [306.00002747 257.89810872]
 [125.99998606 128.18737132]
 [108.00000242 

Epoch 00041: early stopping
[[ 306.99996437  332.8380115 ]
 [ 389.99991618  465.54811064]
 [ 267.00003576  321.6394573 ]
 [ 374.99992058  482.52794943]
 [ 512.99992205  570.01618738]
 [ 374.99992058  329.45858869]
 [1016.00026714  869.31921149]
 [  28.00000147   48.64113236]
 [ 615.99993438  469.50683719]
 [ 164.99998246  168.09723758]
 [ 357.0000797   413.5410958 ]
 [ 344.00003006  446.66296406]
 [  25.00000005   29.5739806 ]
 [ 276.00001991  299.26363401]
 [ 157.00002043  172.84309638]
 [ 145.00001233  143.47770752]
 [ 623.00000063  587.6880568 ]
 [ 608.99995221  469.30990503]
 [  54.99999863   72.90912643]
 [ 272.99999164  314.87703023]
 [  25.99999997   22.72402668]
 [ 461.99991302  460.23719488]
 [ 101.00001138  114.76691586]
 [  54.0000012    38.56042343]
 [ 117.00001197  112.60098889]]
validate rmse: 0.7864238020912387
[[392.63513184 357.80325317 359.92306519 361.628479  ]
 [239.23751831 213.682724   208.08439636 211.4699707 ]
 [450.25784302 396.32727051 398.18597412 401.8721618

Epoch 00237: early stopping
[[ 33.00000086  61.12909663]
 [197.00001339 156.53011752]
 [150.99998997 230.59499297]
 [ 67.00000159  89.3078926 ]
 [193.00004207 164.61337723]
 [ 61.99999271  77.31433359]
 [ 98.9999945  150.94711413]
 [181.99996076 170.9186502 ]
 [ 54.0000012  194.24471842]
 [141.99999548 128.54511932]
 [427.00009893 501.46644761]
 [115.00000242 132.29435697]
 [266.00003849 311.76787733]
 [ 64.00000005 123.03785923]
 [451.00003943 466.85185168]
 [ 39.99999472  70.07597261]
 [108.00000242 140.64778713]
 [108.00000242 159.78433428]
 [201.00004198 162.59401565]
 [198.99994855 179.57695136]
 [166.99998773 229.25764906]
 [334.00006454 367.54991923]
 [130.99999944 143.23503528]
 [315.99995776 253.61486973]
 [ 56.00000294  85.34960437]
 [ 47.99999611  36.21664572]
 [132.00000346 173.62472222]
 [ 53.00000147  63.33041566]
 [118.00000109  93.18958067]]
validate rmse: 0.699016529294566
9 car:04e66e578f653ab9
train shape: (264, 1, 10)
label shape: (264, 1)
test shape: (22, 1, 10)
ba

train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
[[ 378.00002814  405.37554086]
 [ 213.00003262  345.67135877]
 [ 526.99993064  419.89001522]
 [ 610.0000289   605.63072907]
 [ 134.99998513  190.7832687 ]
 [ 646.00005078  581.94250641]
 [ 381.9999341   202.91312262]
 [ 542.9999965   296.31970773]
 [1242.99970411 1086.17223647]
 [1291.99975739 1090.73574904]
 [ 819.99987535  854.99253415]
 [1052.9999362   744.55888593]
 [  94.99999621  171.1786566 ]
 [ 209.00004177  283.11578958]
 [2620.9998463  2596.78023226]
 [ 466.00000584  286.60074466]
 [ 360.00008578  403.0320705 ]
 [ 986.00020072  536.46109372]
 [ 481.99989796  357.9233187 ]
 [ 218.00000576  425.17187413]
 [1214.00004624  991.0067405 ]
 [1012.00026421  972.44194774]
 [ 344.99997916  445.9670456 ]
 [ 446.00009205  254.46261421]
 [3829.00096947 2937.98880141]
 [2859.00072267 2548.84865276]
 [ 373.99993532  742.94601258]
 [ 795.99979445  802.27734989]
 [ 947.99979608  566.33980132]
 [ 439.0000486

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00043: early stopping
[[1201.99997436  800.08892455]
 [ 954.00012556 1125.80957409]
 [ 292.99992504  305.80124634]
 [ 393.99992183  393.50518528]
 [1006.99985272 1212.30503163]
 [ 263.00002952  285.78651306]
 [ 213.99998516  203.69799368]
 [  53.00000147   82.65441376]
 [ 193.9999825   299.99645793]
 [ 124.9999837   106.48741347]
 [1711.00038759 1040.69004318]
 [ 689.00001829  479.59117947]
 [ 266.00003849  342.06515897]
 [ 308.00004924  275.45235892]
 [ 109.99999728  276.03680478]
 [ 178.99996676  156.76343047]
 [ 869.9997714  1169.05512689]
 [ 444.00009413  306.0044318 ]
 [ 383.99996909  216.94481439]
 [1225.00013021  784.03915997]
 [ 360.99997051  299.40245815]
 [ 306.99996437  320.02580261]
 [ 485.00002132  431.84344108]
 [  86.00000749   74.47721546]
 [  46.99999671   78.93875952]]
validate rmse: 0.5665397136994598
[[1620.30456543 1471.64733887 1518.06506348 1407.2286377 ]
 [ 384.47683716  

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00328: early stopping
[[ 143.00001517  246.81259503]
 [ 280.99994826  284.67669562]
 [ 462.99991421  405.29191997]
 [  76.00000704   82.64293659]
 [ 350.00001899  412.9795508 ]
 [ 304.00002826  338.95052406]
 [ 212.00000596  186.10023324]
 [ 198.99994855  251.5563834 ]
 [ 618.00003046 1058.38899003]
 [ 409.00003513  377.70534323]
 [1458.00006486 1328.42485577]
 [ 379.99998495  333.43097367]
 [ 535.00003465  520.84969014]
 [ 229.99994357  322.50167825]
 [ 439.99998925  460.43449253]
 [ 223.99995213  181.18391505]
 [ 233.9999616   277.18355999]
 [ 586.99986225  462.41163388]
 [ 385.00001051  319.83973339]
 [1467.99982251 1449.42998315]
 [ 687.99987684  613.21145454]
 [1202.99997605  969.85604501]
 [ 188.00003701  221.64583217]
 [ 360.00008578  447.59683975]
 [ 289.99994741  225.62380901]
 [ 284.99996542  222.81972383]
 [1372.00021508 1428.45561103]
 [ 197.99998904  188.86399767]
 [  79.99998946  

average rmse: 0.6176959341438246
16 car:12f8b7e14947c34d
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00108: early stopping
[[ 385.00001051  553.40175522]
 [ 215.00004756  505.12572433]
 [ 388.99995138  315.36569672]
 [ 385.00001051  268.69974257]
 [  86.99998863  122.8533979 ]
 [ 977.99985426  782.07306431]
 [ 663.99983839  553.00246052]
 [ 251.99997215  227.23206022]
 [ 160.99999017   90.91612077]
 [ 358.000029    297.948805  ]
 [1280.00017328 1018.83248328]
 [ 228.00000256  206.76509181]
 [ 231.99998868  208.42449414]
 [ 197.99998904  221.63035446]
 [ 195.00001004  188.44563576]
 [ 247.99997092  232.03795977]
 [ 648.99990267  535.52962216]
 [ 491.99995021  453.82486976]
 [1285.99968004  900.95462497]
 [ 284.00006671  282.99085299]
 [ 842.99977614  738.27628864]
 [ 990.99987283 1762.92023544]
 [ 231.00001805  164.46154886]
 [ 328.00008099  248.77045706]
 [ 291.00002758  204.87062083]
 [ 130.0000173   344.57044434]
 [ 611.00011933  662.1

Epoch 00062: early stopping
[[ 668.99990517  583.44902482]
 [2581.99950812 2373.2426346 ]
 [ 284.00006671  325.37114124]
 [ 432.00000981  410.70989491]
 [2367.99943399 2409.79876332]
 [ 297.00003849  286.09701167]
 [ 297.99995267  309.11476482]
 [ 312.99999516  321.85350938]
 [ 190.00004309  233.54734305]
 [ 743.99985217  746.85535923]
 [2952.99968352 2574.37722148]
 [ 332.00000764  382.12376481]
 [ 264.00000696  275.17218833]
 [ 315.99995776  306.55923068]
 [ 472.0000045   343.11343687]
 [ 342.00006709  322.33839685]
 [ 616.99999424  720.24182473]
 [ 352.00003806  256.70535016]
 [ 188.99996367  172.08576605]
 [ 676.00017861  628.45738125]
 [ 270.00004226  281.4839028 ]
 [  88.00000949  121.61487263]
 [ 315.99995776  279.70109102]
 [ 325.00000021  340.23619676]
 [ 250.99995133  216.78250451]]
validate rmse: 0.8443001844439513
[[2588.53173828 2447.47631836 2886.3840332  2583.94482422]
 [ 304.87039185  312.28536987  291.32183838  299.88980103]
 [ 734.13049316  734.27172852  752.36022949 

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
[[ 201.00004198  439.44819427]
 [1227.00000547 1056.18299655]
 [1253.99981444  990.6956299 ]
 [ 789.0000243   635.98437053]
 [1186.99996599 1715.49745446]
 [ 218.99996439  273.80596213]
 [ 565.00003123  541.2694641 ]
 [ 990.99987283 1050.34986243]
 [ 341.0000874   945.86504339]
 [1042.99988864 1614.73347987]
 [1671.00014179 2117.70855779]
 [ 671.00001371  925.03257149]
 [1013.99991491 1098.56031264]
 [ 304.00002826  498.98890932]
 [1610.00011814 1509.85924331]
 [ 229.00004815  356.38705033]
 [ 444.00009413  549.27825298]
 [ 253.00006598  439.8360662 ]
 [1307.00008176 1089.42943756]
 [2001.00004553 1997.69603761]
 [ 312.99999516  494.57881182]
 [1480.99978913 1272.9770755 ]
 [1109.99979249  888.57907637]
 [1628.99985686 1439.82456632]
 [ 895.99980879 1429.1411064 ]
 [ 250.00003408  265.16332586]
 [1490.0003606  1794.55728306]
 [ 267.99993502  296.06139515]
 [ 925.00002648  766.45006714]]
validate rmse

average rmse: 0.7361098740244748
21 car:7245e0ee27b195cd
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00468: early stopping
[[ 576.00006016  738.13619488]
 [ 163.99999676  348.82525098]
 [ 360.00008578  283.99628188]
 [ 238.99995737  241.99398887]
 [  60.99999469   93.78989452]
 [1432.00011643 1339.46528946]
 [ 719.99997976  755.52002567]
 [ 299.99997623  255.61674394]
 [ 798.00005049  588.57908417]
 [ 654.99991058  534.21802628]
 [ 405.99989305  396.67617727]
 [ 342.00006709  469.15306903]
 [ 284.99996542  336.84934755]
 [ 266.00003849  277.74458282]
 [ 836.00016733  792.89974902]
 [ 420.99990696  439.14820921]
 [ 491.99995021  413.37645257]
 [ 887.99995171  898.52050086]
 [1157.99984966  742.40639458]
 [ 516.99988159  536.33413549]
 [1071.0001519  1019.7393499 ]
 [ 542.9999965   946.31995939]
 [ 589.99992742  427.47176964]
 [ 444.00009413  412.64967706]
 [1391.00027233  938.9038063 ]
 [ 718.00000846 1322.13297843]
 [ 930.0001877  1194.6

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00317: early stopping
[[ 88.99999544 154.5330377 ]
 [ 25.99999997  30.00375203]
 [114.00000126 109.90410631]
 [175.00000947 190.12223197]
 [ 37.00000098  69.51099313]
 [148.00000398 106.77853848]
 [ 65.00000864  63.25345572]
 [ 28.00000147  31.16133108]
 [153.99998355 141.74467179]
 [ 50.99999513 107.89435108]
 [ 30.00000159  41.92820178]
 [ 88.00000949  59.93108377]
 [175.00000947  13.90583416]
 [100.00000022  67.54630029]
 [ 65.00000864  94.98358947]
 [ 74.00000198 133.11467756]
 [188.00003701 148.94784052]
 [ 91.00000462 120.1977066 ]
 [105.00001102 100.13068975]
 [360.00008578 221.31194269]
 [  2.99999996   8.97263214]
 [  5.99999991  18.37114391]
 [ 28.00000147  19.9063157 ]
 [153.00001371  54.7458906 ]
 [ 19.00000175  17.49025963]]
validate rmse: 0.42431320852351084
[[228.44497681 108.40046692  76.54892731  18.81283569]
 [372.47219849 241.22093201 144.55981445  82.04907227]
 [614.16546631 

24 car:cd5841d44fd7625e
train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00048: early stopping
[[ 262.00006876  471.27239786]
 [ 537.00014281  468.65889094]
 [1805.99962308 1562.70471468]
 [ 444.00009413  557.37612619]
 [ 491.99995021  478.63188234]
 [ 250.99995133  354.58678142]
 [ 392.99996632  457.38366671]
 [ 481.99989796  483.93521897]
 [ 322.00006621  724.15753875]
 [ 398.99991883  453.63693356]
 [1295.9999239  1275.65695591]
 [ 423.99989897  408.4903829 ]
 [1627.00032684 1557.31756187]
 [ 314.99992343  500.32655208]
 [1641.99993876 1380.48847389]
 [ 291.00002758  305.39137292]
 [ 374.99992058  454.36516602]
 [1033.00008916 1219.04993334]
 [ 629.00000798  476.32505012]
 [1277.99975122  873.57959888]
 [1266.99982345 1241.62421169]
 [1336.00025859 1073.4470816 ]
 [ 768.000143    507.66485356]
 [1780.00014848 1757.16038848]
 [ 335.00005295  368.69142998]
 [ 780.99985083  826.12489168]
 [ 877.9998634   862.38190818]
 [ 236.99994895  308.614

 [ 340.57055664  303.94094849  370.68893433  369.42572021]]
average rmse: 0.6600492176430015
26 car:a207df29ec9583f0
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00086: early stopping
[[ 353.99997444  201.09992946]
 [  86.99998863   98.68521958]
 [ 746.99989529  681.48756689]
 [ 226.99996782  251.98103152]
 [ 726.00009697  827.41050667]
 [ 203.0000006   225.43181128]
 [ 439.99998925  499.42454171]
 [ 329.99996496  327.37820613]
 [ 210.00002206  287.66898682]
 [ 314.99992343  274.00994425]
 [1071.99974041 1017.03092758]
 [ 383.99996909  358.50401567]
 [ 164.99998246  171.46259319]
 [ 222.99998655  253.4841683 ]
 [ 964.00005301  864.57294054]
 [ 175.00000947  262.8361872 ]
 [ 250.99995133  240.31558929]
 [ 286.99993272  275.62494727]
 [ 215.9999473   223.35749663]
 [ 218.99996439  232.50004685]
 [ 488.00008781  434.94713407]
 [1590.99975675  936.48196743]
 [  96.99999124  123.8928148 ]
 [ 163.99999676  193.2582481 ]
 [ 946.00018406 1033.046

27 car:3e21824be728cbec
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00092: early stopping
[[472.99996588 324.27247072]
 [379.99998495 357.41538508]
 [188.00003701 146.93129548]
 [394.99989484 426.2186969 ]
 [411.00009365 430.15175344]
 [181.99996076 194.28199916]
 [225.99998218 199.37360349]
 [ 38.99999677  72.78404556]
 [374.99992058 468.73434626]
 [ 64.00000005  70.20700903]
 [525.00012558 443.44966527]
 [398.00000325 387.08280945]
 [162.99998896 129.28825018]
 [199.99994716 152.59128752]
 [ 86.99998863  94.21493238]
 [173.99997729 184.41181387]
 [640.99998381 879.88528896]
 [454.99996294 417.08360037]
 [240.0000128  185.75947532]
 [542.9999965  428.83024139]
 [175.99997209 142.97707172]
 [135.99999815 201.53843434]
 [224.99996378 182.3393626 ]
 [ 74.00000198  38.44262413]
 [ 67.00000159  80.45542101]]
validate rmse: 0.7363919432246702
[[411.2585144  433.49267578 348.3744812  320.82876587]
 [174.90803528 167.25784302 156.28219604 117.62

Epoch 00058: early stopping
[[ 362.99995168  618.49076503]
 [ 208.00005528  282.57916415]
 [ 667.99995115  547.07024278]
 [ 141.00001623  161.00235039]
 [ 525.99991892  490.34359583]
 [ 387.00007376  506.47792814]
 [ 232.99994078  251.20528855]
 [ 204.99996877  236.17399381]
 [ 451.00003943  918.86953318]
 [ 641.99990319  570.7462303 ]
 [1181.00012579 1056.65829938]
 [ 715.99986726  685.04175063]
 [ 891.99994648  746.82271308]
 [ 364.00001861  650.9554855 ]
 [1739.00038827  802.79243794]
 [ 498.00010356  556.58217948]
 [ 309.99992256  401.04277984]
 [ 335.99999034  425.29836361]
 [1490.0003606   612.2769357 ]
 [ 454.00005671  567.56443651]
 [ 427.00009893  554.54194838]
 [1586.00028293 1162.89861829]
 [ 191.00001793  216.64745453]
 [ 504.99999014  466.5311702 ]
 [ 292.99992504  334.20417014]
 [ 206.00002693  256.88248748]
 [ 799.9997889   718.08077331]
 [ 429.99998057  507.90278882]
 [ 429.99998057  202.4924589 ]]
validate rmse: 0.5004090002816719
29 car:b25c4e2e3856af22
train shape: (

31 car:fde95ea242abd896
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00102: early stopping
[[ 387.00007376  423.32642729]
 [  89.99999743  148.2968699 ]
 [ 301.00004187  234.16804716]
 [ 795.99979445  565.92694787]
 [ 130.0000173   187.79750385]
 [ 601.99992338  463.73749143]
 [ 616.99999424  437.83033245]
 [ 765.0001713   658.66379609]
 [ 541.99996041  391.91270268]
 [1066.00026157  727.4125257 ]
 [ 697.99999189  646.34485581]
 [ 773.99994133  696.86864379]
 [ 286.00003039  312.21842949]
 [ 231.99998868  306.67985844]
 [3040.00069132 2803.8485298 ]
 [ 508.99997632  346.00947508]
 [ 155.00000257  136.76118137]
 [ 499.00008146  393.93943701]
 [ 292.99992504  152.20527476]
 [ 401.00002467  472.0437872 ]
 [ 570.00008285  470.11040914]
 [ 690.00014234  904.76792625]
 [ 220.99999662  203.67790608]
 [ 280.00005231  322.9240149 ]
 [3591.99999466 3061.73516467]
 [3228.99959077 4111.84230169]
 [ 400.000001    475.58824098]
 [ 643.99996087  590.206

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00082: early stopping
[[ 821.99996833  840.97144955]
 [2551.00043987 2862.13745726]
 [ 614.99985624  797.303555  ]
 [1538.99964082 1766.18709612]
 [2464.99951839 3272.56110141]
 [ 807.99987609  740.36115476]
 [ 817.00014657  625.31409785]
 [ 520.99992247  446.03290317]
 [1047.00018148  908.54748033]
 [ 512.00000064  455.49260727]
 [3185.0007558  3894.69767119]
 [ 423.00001424  573.85683447]
 [ 216.99998578  230.43893079]
 [ 742.99987713  777.69326684]
 [ 198.99994855  220.7859212 ]
 [ 691.99995217  626.97834901]
 [1324.99968636 1263.92234554]
 [1268.99993939 1065.01591878]
 [ 519.99993075  485.09698465]
 [1019.99976803  998.2398634 ]
 [ 157.00002043  244.11342721]
 [ 141.00001623  192.14082   ]
 [ 322.00006621  400.29778277]
 [ 667.99995115  490.68875414]
 [ 461.99991302  379.02808472]]
validate rmse: 0.7308961622076804
[[3766.70776367 3501.38793945 2893.68383789 2531.76904297]
 [1033.10461426  

Epoch 00073: early stopping
[[ 153.99998355  349.54525229]
 [1391.00027233  532.59866301]
 [3284.00075335 3415.58289993]
 [ 678.99997411  490.73924082]
 [ 464.00010112  521.17603546]
 [ 231.99998868  313.6756459 ]
 [ 553.00010217  707.95711317]
 [ 776.99999794  637.04675834]
 [ 254.99994193  530.22926864]
 [ 392.99996632  515.61243962]
 [ 954.99996336 1177.90923282]
 [ 448.00002373  763.99599925]
 [2824.99978257 3308.57479912]
 [ 474.99991823 1075.50851944]
 [5495.99924572 3897.36024262]
 [ 315.99995776  497.55059513]
 [ 404.00004566  529.54314695]
 [ 114.00000126  199.55308784]
 [1668.99977073 1035.04840711]
 [ 891.99994648  492.15471653]
 [ 158.99999147  318.8105519 ]
 [1166.99975912 1270.44910231]
 [ 930.0001877   666.90016368]
 [5099.00050083 3759.31481033]
 [ 346.00006825  450.64171805]
 [ 775.99993026  630.75375319]
 [ 614.00009249  467.47418884]
 [ 235.99993931  450.19055682]
 [ 940.99977284  496.78783845]]
validate rmse: 0.5526265936644534
34 car:ea489c253676aafc
train shape: (

36 car:cc21c7e91a3b5a0c
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00123: early stopping
[[ 403.00005947  408.27529524]
 [ 193.00004207  241.76602119]
 [ 356.00007678  233.898445  ]
 [ 734.00010678  549.19041749]
 [ 126.99999948  228.1162262 ]
 [ 574.00001853  481.76048588]
 [ 561.00000674  505.5845021 ]
 [ 724.00005452  638.3283221 ]
 [ 510.00001987  490.42829402]
 [1188.99991777  826.99467778]
 [1242.99970411 1159.35686259]
 [1129.00025551 1137.39758689]
 [ 504.99999014  412.1049398 ]
 [ 358.99990848  305.35735013]
 [2284.00013386 2550.27980357]
 [ 224.99996378  300.6937257 ]
 [ 346.00006825  294.23879593]
 [ 701.99982763  555.39397153]
 [ 496.00007412  313.26774268]
 [ 483.99997513  417.15875748]
 [ 952.99981047  768.93989091]
 [ 877.00022552 1277.90778253]
 [ 309.99992256  293.83502158]
 [ 243.99997883  262.24907285]
 [2188.99966939 2175.17132492]
 [1929.99965136 2963.80411054]
 [ 842.00003848  677.40054884]
 [ 497.00001006  590.272

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00336: early stopping
[[ 739.00000483  673.23144413]
 [1873.00037843 1632.80869582]
 [ 474.99991823  417.61287863]
 [ 627.99991453  622.93159017]
 [1066.99973392 1239.14925343]
 [ 444.00009413  396.09656772]
 [ 342.00006709  408.10839738]
 [ 413.00002531  416.58164055]
 [ 406.99994609  353.2286158 ]
 [ 852.00013075  923.06467375]
 [2201.00025754 1943.84584215]
 [ 750.00004118  740.86650544]
 [ 110.99999391  255.85067954]
 [ 530.00008598  439.6431421 ]
 [ 672.00015989  718.77319731]
 [ 475.99989144  436.66024134]
 [ 406.99994609  572.35952302]
 [1094.00022005  788.41056499]
 [ 286.00003039  257.40310677]
 [ 673.99989656  648.75534951]
 [ 188.99996367  255.01040914]
 [ 447.00001168  454.99656725]
 [ 322.00006621  330.11820159]
 [ 507.99999809  352.35843205]
 [ 271.99999635  235.39232277]]
validate rmse: 0.8143376343565476
[[1842.78552246 1621.65039062 1689.53125    1060.17102051]
 [ 521.02832031  

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00228: early stopping
[[ 201.99996896  476.3616158 ]
 [ 449.0001188   389.60801282]
 [ 842.99977614  881.53459788]
 [ 225.99998218  274.07188441]
 [ 537.00014281  683.46926308]
 [ 130.99999944  242.60881701]
 [ 203.99998059  200.08280468]
 [ 295.00004229  377.24192662]
 [ 185.99996299 1060.02023206]
 [ 368.00005663  480.44072122]
 [ 875.99985785 1126.07667019]
 [ 209.00004177  431.05110776]
 [ 841.00014147  872.47103781]
 [ 344.00003006  631.32393958]
 [1740.00000684 1516.76227684]
 [ 198.99994855  333.63206371]
 [ 175.99997209  317.91803115]
 [ 278.99999608  415.47343007]
 [1596.99967069 1066.94058093]
 [1566.00037537  961.77492226]
 [ 289.00006896  412.06232326]
 [ 938.99990901  711.94720814]
 [ 450.00004757  266.98395273]
 [ 977.99985426 1583.41612072]
 [  77.99999355  240.39643843]
 [ 160.99999017  144.1113264 ]
 [ 703.99988858  793.74767093]
 [ 229.00004815  290.05065826]
 [ 485.00002132  

average rmse: 0.5455308125862142
41 car:0797526c057dcf5b
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00153: early stopping
[[  358.000029     509.11883575]
 [  163.99999676   302.47809489]
 [  655.99998724   604.67037084]
 [ 1590.99975675  1344.59475293]
 [  344.00003006   391.00932991]
 [ 2448.99938394  1654.42894467]
 [ 1178.99980295   868.19522983]
 [ 1475.99973044  1335.4021505 ]
 [ 3014.00045331  2054.05501792]
 [ 1424.99963864   903.66265994]
 [ 2259.00039831  1907.35500189]
 [ 1051.00012938  1045.17834727]
 [ 1188.99991777  1022.66866634]
 [  208.00005528   195.86335167]
 [ 6811.99996457  7156.42796308]
 [  353.99997444   253.77201686]
 [  325.99997797   316.29471901]
 [ 1289.99983666  1328.78535537]
 [  722.00013356   354.48094459]
 [ 1475.99973044  1383.55841338]
 [ 2012.00000877  1971.37449314]
 [ 1246.99971479  2284.02204989]
 [  774.99991034   598.51785586]
 [ 1467.00005272  1343.54150727]
 [10484.99983022  8774.57687352]
 [ 

42 car:5b1c11c3efed5312
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00207: early stopping
[[410.00004689 341.09808078]
 [247.0000225  240.64620458]
 [138.00000994 149.81846489]
 [246.00004064 278.91419272]
 [246.00004064 268.10010208]
 [137.00000586 136.99182654]
 [101.99999028  65.91742573]
 [ 33.99999953  25.77801433]
 [271.99999635 223.41334606]
 [ 54.99999863  59.90800581]
 [535.00003465 619.56851643]
 [172.99998799 180.77369973]
 [ 91.99998961  83.45362518]
 [112.99999107  96.74328806]
 [ 50.99999513  72.42120671]
 [ 62.99999302  76.35722499]
 [401.99997688 398.63382053]
 [321.0000371  221.30451029]
 [312.99999516 193.19428215]
 [778.99984878 687.72229714]
 [ 83.00000188  75.68160816]
 [ 14.00000073  21.77560117]
 [126.99999948  85.46194463]
 [ 50.0000001   32.11443646]
 [114.00000126  82.38963391]]
validate rmse: 0.7724418097250252
[[ 584.17590332  430.61923218  246.72990417  152.73013306]
 [ 305.74429321  152.20271301   97.70733643

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
[[ 193.00004207  311.24794942]
 [ 103.9999999    79.68473137]
 [ 561.00000674  435.18323255]
 [ 126.99999948  107.5056972 ]
 [ 379.99998495  425.67465409]
 [ 658.00016377  504.74000545]
 [ 139.00001451  115.51681899]
 [ 209.00004177  126.33216527]
 [ 554.00005663 1141.75506087]
 [ 401.99997688  533.75858889]
 [ 807.99987609  879.38730113]
 [ 531.00005987  297.29878828]
 [ 752.00014826  710.66330005]
 [ 108.00000242  150.54796496]
 [ 713.99996921  705.64481438]
 [ 195.00001004  189.86943046]
 [  57.99999715   92.45926933]
 [ 404.99992241  587.41462367]
 [ 192.00003569  171.85914597]
 [2769.00042064 2123.90852917]
 [ 462.99991421  495.11747678]
 [ 785.00020757  762.45359863]
 [ 182.99996917  133.50763283]
 [ 469.00003563  525.34559412]
 [ 261.00001421  311.86944007]
 [ 231.99998868  282.37211438]
 [2543.00057785 1364.69565307]
 [ 177.99999092  229.85506656]
 [ 114.00000126  123.22571772]]
validate rmse

label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00202: early stopping
[[ 495.00003899  434.24284769]
 [ 114.00000126  185.72937435]
 [ 753.99996206  693.84760332]
 [ 611.99989192  495.20959916]
 [ 385.00001051  417.6195573 ]
 [ 970.9998265   853.90710463]
 [ 352.99990714  254.69318545]
 [ 322.00006621  426.08466527]
 [1150.00017879  822.03852999]
 [ 778.99984878  620.93870379]
 [ 895.00019254  815.82594437]
 [ 489.00005739  425.2346608 ]
 [ 187.00001748  173.85640446]
 [ 119.00000454  120.02374138]
 [2459.99942573 2032.58392992]
 [ 114.00000126  125.44579727]
 [ 178.99996676  202.596112  ]
 [ 488.00008781  473.85475605]
 [ 370.99993079  217.83063581]
 [ 431.00009872  370.88444989]
 [ 727.00005764  739.45593972]
 [1069.99978428 1228.95007922]
 [ 297.00003849  300.75736888]
 [ 235.00001511  216.69746751]
 [2998.99921137 2406.06728921]
 [2665.99991866 2979.78547766]
 [ 652.00012982  685.95384897]
 [ 487.00008622  379.29529119]
 [ 845.99980313  713.48061467]
 [ 178.99996

47 car:af6f4f548684e14d
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
[[ 986.00020072  929.77067775]
 [ 837.99997497  966.27411424]
 [1084.00020992 1053.65858398]
 [1018.99977723 1231.42304694]
 [ 891.99994648  997.75254205]
 [1068.00014336  964.89000299]
 [ 355.00003633  405.46782476]
 [ 143.00001517  183.80978996]
 [ 404.00004566  470.23923812]
 [ 438.0000456   352.09518623]
 [1472.00022698 1638.58539009]
 [1018.00022413 1133.25185448]
 [ 806.99991589  869.55234064]
 [ 893.00002009  903.75563727]
 [ 601.00014728  573.99389882]
 [ 432.99993244  385.61826431]
 [1181.00012579 1281.6080941 ]
 [ 690.99987634  694.46556988]
 [1127.0002904   927.32642262]
 [1265.00016258 1378.08635288]
 [ 869.9997714   851.49704472]
 [ 311.9999743   324.13317335]
 [ 398.00000325  398.63679558]
 [ 253.00006598  246.96855529]
 [ 404.00004566  425.49588029]]
validate rmse: 0.8775922427555221
[[1032.49902344 1001.47436523  976.41308594  830.13861084]
 [1057.82165527 1036.

train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00386: early stopping
[[ 188.99996367  249.33856072]
 [ 318.99993356  291.95764025]
 [ 531.00005987  370.74647364]
 [ 231.99998868  267.96179278]
 [ 221.99998786  283.3058653 ]
 [  85.00001022  124.00395161]
 [ 276.99995444  250.6736851 ]
 [ 289.99994741  301.38763349]
 [1158.99969738 1738.58698492]
 [ 286.00003039  252.94963005]
 [ 461.00010567  415.58152633]
 [ 275.00003008  261.3530953 ]
 [ 400.000001    397.37609059]
 [  83.00000188  133.28917741]
 [ 400.000001    380.49457681]
 [ 112.99999107  109.33281554]
 [ 225.99998218  295.87159382]
 [ 503.00000204  550.2653174 ]
 [ 138.00000994  134.72014956]
 [1679.9997295  1797.26949087]
 [ 627.00007424  623.6981501 ]
 [ 469.99990502  424.32301201]
 [ 201.00004198  279.32426458]
 [ 362.99995168  437.34163681]
 [ 188.00003701  180.61592021]
 [ 489.00005739  473.23805167]
 [1985.00000705 1725.74835198]
 [ 112.0000059    99.99331031]
 [ 232.99994078  

average rmse: 0.6774997632386508
51 car:ef76a85c4b39f693
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00110: early stopping
[[ 304.00002826  216.52830155]
 [  79.00001047   93.03987415]
 [ 310.99999849  463.45131239]
 [ 138.00000994  177.21963998]
 [ 542.9999965   501.03945066]
 [ 297.99995267  315.56009714]
 [ 643.0000113   565.42034659]
 [ 308.00004924  244.99796878]
 [ 531.00005987  558.28994012]
 [ 212.00000596  216.90850377]
 [1045.99992679  899.81084568]
 [ 436.99999092  357.43367647]
 [ 209.00004177  167.50373205]
 [ 192.00003569  158.97791316]
 [ 641.99990319  643.95601966]
 [ 213.00003262  261.18638043]
 [ 247.0000225   218.52148661]
 [ 292.99992504  232.54491773]
 [ 204.99996877  194.26221877]
 [ 267.00003576  269.66115324]
 [ 478.99994766  396.03174982]
 [ 992.99984555  610.9424712 ]
 [  93.00000627   96.79190665]
 [ 206.00002693  249.12558578]
 [ 958.00015082  935.05130325]
 [ 597.99993162  633.58147266]
 [ 423.00001424  373.1

52 car:28e29f2c03dcd84c
train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
[[ 814.00010927  765.02667909]
 [ 388.99995138  365.00478648]
 [ 428.00008446  460.82270889]
 [1140.99998227 1191.93881141]
 [ 548.99986279  366.28656469]
 [ 452.0000849   400.96240389]
 [ 369.99996096  386.56275581]
 [ 122.99998751  124.22033274]
 [ 883.99998676  856.03964123]
 [ 216.99998578  216.51514332]
 [ 555.00004409  478.94683895]
 [ 738.00006181  703.59394499]
 [ 667.00006949  726.30706472]
 [ 394.99989484  410.99505449]
 [1308.00027686 1383.48687336]
 [ 551.00002384  525.36071706]
 [1288.00026525 1611.22961036]
 [1590.00012847 1576.95604737]
 [ 372.00002518  281.92735822]
 [ 823.00008861  660.53862818]
 [ 516.99988159  594.75180116]
 [ 310.99999849  373.87016714]
 [ 259.00002041  257.58965093]
 [  91.00000462  118.07000171]
 [ 727.00005764  859.90896428]]
validate rmse: 0.8464390882251172
[[ 540.35638428  546.91143799  494.38839722  537.51702881]
 [ 472.3338623   479.

54 car:bb9fbec9a2833839
train shape: (286, 1, 10)
label shape: (286, 1)
test shape: (22, 1, 10)
batch_size: 11
Epoch 00043: early stopping
[[ 177.00003437  320.68225692]
 [ 201.00004198  172.1638963 ]
 [ 306.99996437  300.77452439]
 [ 177.99999092  135.48077768]
 [ 299.00004546  245.74288374]
 [ 201.99996896  229.33208843]
 [ 137.00000586  166.82977146]
 [ 197.99998904  153.77779222]
 [ 271.0000524   618.89907338]
 [ 332.00000764  233.42237945]
 [1098.00001841  691.22829549]
 [ 250.99995133  258.65287589]
 [ 413.00002531  391.52973028]
 [ 139.00001451  245.5918869 ]
 [ 507.00009251  371.60937094]
 [ 145.00001233  174.29588719]
 [ 158.00002097  172.92276884]
 [ 278.99999608  315.63058847]
 [ 309.99992256  234.76599566]
 [ 863.99978947  541.41952521]
 [ 259.00002041  360.88625562]
 [ 551.99989278  713.44258158]
 [ 225.99998218  155.61086759]
 [ 398.00000325  291.26277415]
 [  91.99998961  116.90200712]
 [ 163.99999676  167.94738854]
 [ 788.00005381  541.24840116]
 [ 141.99999548  169.487

validate rmse: 0.6194276748722208
[[416.77886963 316.94555664 250.9916687  216.60211182]
 [329.5067749  229.09024048 153.4894104  127.22787476]
 [734.17077637 612.19189453 490.0453186  383.94628906]
 [367.26596069 263.60943604 172.75547791 165.2567749 ]
 [799.50189209 564.26916504 398.64764404 329.90911865]
 [174.22790527 150.01568604  84.70848846  69.36888123]
 [394.00634766 302.97488403 234.50488281 200.80966187]
 [155.93917847 146.4793396   94.23691559  77.08166504]
 [286.91473389 247.77005005 178.60704041 142.32653809]
 [117.79022217  95.92355347  67.55948639  62.83319092]
 [ 50.76799393  52.51010895  41.0992775   36.08896255]
 [307.46542358 228.83067322 160.88961792 137.93167114]
 [313.02362061 247.92388916 201.28890991 179.08999634]
 [ 76.82241058  71.59902954  45.23830795  38.85340881]
 [371.86306763 286.52981567 219.5609436  187.51663208]
 [ 72.04129028  66.17588043  42.49443817  40.53422928]
 [550.55975342 327.74502563 223.71026611 158.77915955]
 [ 64.57813263  56.71300888  35

train shape: (264, 1, 10)
label shape: (264, 1)
test shape: (22, 1, 10)
batch_size: 10
Epoch 00042: early stopping
[[1157.99984966 1036.48066764]
 [ 203.0000006   213.57717117]
 [ 895.99980879  911.13212856]
 [ 356.00007678  371.93835738]
 [ 875.99985785  728.82537118]
 [ 423.99989897  437.91693163]
 [ 229.00004815  276.78548362]
 [ 394.99989484  387.40566836]
 [ 321.0000371   400.31677494]
 [ 801.9998357   649.18813646]
 [1057.0002667  1848.879582  ]
 [ 818.99990822  615.66672263]
 [ 255.99993204  439.51004335]
 [ 469.99990502  351.4712806 ]
 [1728.99978692 1500.22679132]
 [1900.99961828 1301.64831089]
 [ 357.0000797   364.58590995]
 [ 118.00000109  229.06023902]
 [2598.00007592 1800.99647025]
 [ 388.99995138  440.00561859]
 [ 411.99994411  479.3113138 ]
 [ 515.99986545  706.89063955]
 [ 175.99997209  374.93415781]
 [ 341.0000874   455.11130731]
 [ 306.99996437  381.70477612]
 [ 328.00008099  285.90460608]
 [ 497.00001006  496.62923248]]
validate rmse: 0.5955405063107362
57 car:7a7885

59 car:63065128401bb3ff
train shape: (308, 1, 10)
label shape: (308, 1)
test shape: (22, 1, 10)
batch_size: 12
Epoch 00053: early stopping
[[1459.99968889 2199.80029304]
 [ 213.99998516  498.78147229]
 [1494.00018903 1041.22164798]
 [1218.00022926 1058.13287227]
 [ 360.99997051  678.85665299]
 [3711.00066836 2729.74707224]
 [2351.00036181 1620.76068881]
 [1223.00025475  958.11250903]
 [1219.99973282  698.76505318]
 [1466.00018231 1317.06322598]
 [3008.00059398 2897.07026666]
 [1415.00008972 1059.31864258]
 [1333.00031442 1126.74498803]
 [ 826.99996804  821.67489532]
 [1505.999987   1474.37111799]
 [1251.99998102  929.34650613]
 [ 842.00003848 1021.44387489]
 [2429.00015662 2763.65474545]
 [1747.99996423 1093.32509688]
 [1328.00003096 1254.83769995]
 [2268.99946119 2690.11645532]
 [2143.00023071 3771.99748801]
 [1191.99981106 1062.83237288]
 [1615.00034357 1139.57758229]
 [1765.99974434 1281.01453289]
 [ 624.99983587 1992.98396995]
 [2610.99966264 2408.1883986 ]
 [1980.00015659 1023.431

train shape: (242, 1, 10)
label shape: (242, 1)
test shape: (22, 1, 10)
batch_size: 9
Epoch 00044: early stopping
[[ 2418.99997376  1768.34259941]
 [ 9110.00148901  7772.02673572]
 [  748.00007014   821.0619001 ]
 [ 1113.00029505  1065.11641296]
 [ 8732.99883583  8375.61077164]
 [  769.00014934   728.68512857]
 [  429.99998057   442.55605409]
 [  957.00023291   849.25493979]
 [  486.0000612    642.13920847]
 [ 2147.00002896  1796.55394345]
 [10370.99820349  7598.54033403]
 [  950.99979103   803.30956961]
 [  321.0000371    473.85551385]
 [  821.00018808   809.30991715]
 [  469.99990502   450.3163275 ]
 [  571.99990841   482.64345738]
 [ 1828.00021201  2143.54978937]
 [ 1183.00005863   775.61076554]
 [  499.00008146   556.33003996]
 [ 2106.9998415   1827.7108181 ]
 [  423.00001424   443.86614957]
 [  225.99998218   340.76549044]
 [ 1699.00024579  1350.39806114]
 [  891.99994648   887.25612013]
 [  383.99996909   407.57508675]]
validate rmse: 0.6701498087663447
[[ 9518.97753906  9327.039

```
all validation rmse:0.6555167883490066
```

In [8]:
submit = submit.sort_values(by=['id'], ascending=True)
submit['forecastVolum'] = submit['forecastVolum'].map(lambda index: int(np.round(index)))
print('res store over')

res store over


In [9]:
sub = submit.sort_values(by=['id'], ascending=True)
print(len(sub))
sub['forecastVolum'].mean()

5280


597.4863636363636

In [10]:
sub = submit.copy()
sub['forecastVolum'] = sub['forecastVolum'] / thresh
sub['forecastVolum'] = sub['forecastVolum'].map(lambda index: int(np.round(index)))
sub.groupby(['regMonth'])['forecastVolum'].mean()
sub[['id', 'forecastVolum']].to_csv('./submit/chusai_lstm_model_1.csv', encoding='utf-8', index=None)

regMonth
1    483.454545
2    425.534091
3    393.977273
4    380.087121
Name: forecastVolum, dtype: float64